package com.unionpay.mobile.android.model;

import com.unionpay.mobile.android.views.order.l;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONObject;
/* loaded from: classes6.dex */
public final class b {
    public static boolean aA = false;
    public static boolean aB = false;
    public static boolean ba = false;
    public static List<d> bb = null;
    public static boolean bl = false;
    public static boolean bm = false;
    public static boolean bn = false;
    public static boolean bo = false;
    public com.unionpay.mobile.android.plugin.c I;
    public String bk;
    public List<c> q;
    public String a = "1.9";
    public String b = "";
    public boolean c = true;
    public String d = "";
    public String e = "";
    public boolean f = false;
    public String g = null;
    public JSONArray h = null;
    public JSONObject i = null;
    public JSONObject j = null;
    public String k = null;
    public String l = null;
    public String m = null;
    public String n = "";
    public String o = "";
    public HashMap<String, String> p = null;
    public String r = null;
    public String s = null;
    public JSONArray t = null;
    public String u = null;
    public JSONObject v = null;
    public JSONObject w = null;
    public JSONObject x = null;
    public String y = null;
    public JSONArray z = null;
    public String A = "";
    public String B = "";
    public JSONObject C = null;
    public JSONArray D = null;
    public String E = "";
    public boolean F = false;
    public JSONObject G = null;
    public JSONArray H = null;
    public boolean J = false;
    public boolean K = false;
    public boolean L = false;
    public String M = "0";
    public int N = 0;
    public String O = "";
    public String P = null;
    public String Q = null;
    public String R = "";
    public String S = "";
    public JSONArray T = null;
    public boolean U = false;
    public String V = null;
    public String W = null;
    public JSONArray X = null;
    public JSONObject Y = null;
    public JSONObject Z = null;
    public JSONObject aa = null;
    public List<c> ab = null;
    public JSONArray ac = null;
    public JSONArray ad = null;
    public String ae = null;
    public String af = "";
    public String ag = "";
    public int ah = 0;
    public String ai = "";
    public String aj = "";
    public String ak = "";
    public JSONObject al = null;
    public JSONObject am = null;
    public String an = null;
    public int ao = 0;
    public String ap = "";
    public String aq = null;
    public String ar = null;
    public String as = null;
    public String at = null;
    public JSONObject au = null;
    public JSONObject av = null;
    public boolean aw = false;
    public boolean ax = false;
    public boolean ay = false;
    public boolean az = false;
    public boolean aC = false;
    public boolean aD = false;
    public boolean aE = false;
    public JSONObject aF = null;
    public String aG = null;
    public String aH = null;
    public String aI = null;
    public String aJ = null;
    public String aK = null;
    public String aL = null;
    public boolean aM = false;
    public int aN = 0;
    public int aO = 0;
    public int aP = l.a.intValue();
    public int aQ = l.b.intValue();
    public String aR = null;
    public String aS = null;
    public String aT = null;
    public JSONObject aU = null;
    public boolean aV = false;
    public String aW = null;
    public String aX = null;
    public String aY = null;
    public boolean aZ = false;
    public int bc = 0;
    public int bd = 0;
    public int be = 0;
    public String bf = null;
    public String bg = null;
    public String bh = null;
    public String bi = null;
    public String bj = null;
    public String bp = null;
    public String bq = null;
    public boolean br = false;
    public c bs = null;
    public String bt = "";

    public b() {
        this.q = null;
        this.I = null;
        this.bk = "";
        this.I = new com.unionpay.mobile.android.plugin.c();
        this.q = new ArrayList(1);
        bb = new ArrayList(1);
        bm = false;
        bn = false;
        bo = false;
        aA = false;
        aB = false;
        this.bk = "";
    }

    public final String a() {
        return this.I != null ? (this.I.a == 2 || this.I.a == 3 || this.I.a == 5) ? "2" : "1" : "1";
    }
}
