package com.sankuai.meituan.serviceloader;

import android.content.Context;
import android.text.TextUtils;
import com.alipay.sdk.widget.d;
import com.dianping.live.live.mrn.MLivePlayerModule;
import com.dianping.titans.js.jshandler.CaptureJsHandler;
import com.meituan.ai.speech.sdk.knb.KnbConstants;
import com.meituan.android.common.aidata.utils.Constants;
import com.meituan.android.common.locate.locator.GearsLocator;
import com.meituan.android.mrn.knb.CallNativeModuleJsHandler;
import com.meituan.android.mrn.module.jshandler.ABTestStrategyJsHandler;
import com.meituan.android.mrn.module.jshandler.MRNDeepPreLoadJsHandler;
import com.meituan.android.mrn.module.jshandler.MRNInfoJsHandler;
import com.meituan.android.mrn.module.jshandler.MapiRequestJsHandler;
import com.meituan.android.mrn.module.jshandler.RegisterHornJsHandler;
import com.meituan.android.mrn.module.jshandler.RequestJSHandler;
import com.meituan.android.mrn.module.jshandler.SNTPTimeJsHandler;
import com.meituan.android.mrn.module.jshandler.StatisticsJsHandler;
import com.meituan.android.mrn.module.jshandler.pageRouter.ListContainersHandler;
import com.meituan.android.mrn.module.jshandler.pageRouter.OpenUrlWithResultCustomHandler;
import com.meituan.android.mrn.module.jshandler.pageRouter.PageCloseJsHandler;
import com.meituan.android.mrn.module.jshandler.pageRouter.SwitchPageJsHandler;
import com.meituan.android.neohybrid.core.config.UIConfig;
import com.meituan.msi.bean.ContainerInfo;
import com.meituan.robust.ChangeQuickRedirect;
import com.meituan.robust.PatchProxy;
import com.meituan.robust.utils.RobustBitConfig;
import com.sankuai.waimai.alita.core.mlmodel.predictor.bean.TensorConfig;
import com.sankuai.waimai.alita.platform.monitor.AlitaMonitorCenter;
import com.sankuai.waimai.business.ugc.machpro.module.calendar.WMCalendarModule;
import com.sankuai.waimai.pouch.model.PouchDynamicAd;
import com.sankuai.waimai.store.repository.model.ConfigInfo;
import com.tencent.open.SocialConstants;
import com.tencent.smtt.sdk.TbsListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
/* compiled from: ProGuard */
/* loaded from: classes4.dex */
public class b {
    public static ChangeQuickRedirect a = null;
    public static volatile Map<String, Object> b = null;
    private static volatile Map<String, Map<String, String>> c = null;
    private static Context d = null;
    private static volatile boolean e = false;
    private static a f;
    private static ExecutorService g;

    /* compiled from: ProGuard */
    /* loaded from: classes4.dex */
    public interface a {
        void a(Throwable th);
    }

    private static void c() {
        c = new HashMap(91);
        HashMap hashMap = new HashMap(183);
        hashMap.put(CallNativeModuleJsHandler.KEY, "com.meituan.android.mrn.knb.CallNativeModuleJsHandler");
        hashMap.put(PageCloseJsHandler.KEY, "com.meituan.android.mrn.module.jshandler.pageRouter.PageCloseJsHandler");
        hashMap.put(SNTPTimeJsHandler.KEY, "com.meituan.android.mrn.module.jshandler.SNTPTimeJsHandler");
        hashMap.put(ABTestStrategyJsHandler.KEY, "com.meituan.android.mrn.module.jshandler.ABTestStrategyJsHandler");
        hashMap.put(MRNInfoJsHandler.KEY, "com.meituan.android.mrn.module.jshandler.MRNInfoJsHandler");
        hashMap.put(ListContainersHandler.KEY, "com.meituan.android.mrn.module.jshandler.pageRouter.ListContainersHandler");
        hashMap.put(StatisticsJsHandler.KEY, "com.meituan.android.mrn.module.jshandler.StatisticsJsHandler");
        hashMap.put(MapiRequestJsHandler.KEY, "com.meituan.android.mrn.module.jshandler.MapiRequestJsHandler");
        hashMap.put(OpenUrlWithResultCustomHandler.KEY, "com.meituan.android.mrn.module.jshandler.pageRouter.OpenUrlWithResultCustomHandler");
        hashMap.put(MRNDeepPreLoadJsHandler.KEY, "com.meituan.android.mrn.module.jshandler.MRNDeepPreLoadJsHandler");
        hashMap.put(RegisterHornJsHandler.KEY, "com.meituan.android.mrn.module.jshandler.RegisterHornJsHandler");
        hashMap.put(RequestJSHandler.KEY, "com.meituan.android.mrn.module.jshandler.RequestJSHandler");
        hashMap.put(SwitchPageJsHandler.KEY, "com.meituan.android.mrn.module.jshandler.pageRouter.SwitchPageJsHandler");
        hashMap.put("dxsdk.addDownload", "com.sankuai.xm.integration.knb.handler.AddDownloadJsHandler");
        hashMap.put("dxsdk.cancelDownload", "com.sankuai.xm.integration.knb.handler.CancelDownloadJsHandler");
        hashMap.put("dxsdk.cancelMessage", "com.sankuai.xm.integration.knb.handler.CancelMessageJsHandler");
        hashMap.put("dxsdk.cleanSessions", "com.sankuai.xm.integration.knb.handler.CleanSessionsJsHandler");
        hashMap.put("dxsdk.deleteLocalMessage", "com.sankuai.xm.integration.knb.handler.DeleteLocalMsgJsHandler");
        hashMap.put("dxsdk.deleteSession", "com.sankuai.xm.integration.knb.handler.DeleteSessionJsHandler");
        hashMap.put("dxsdk.enterSession", "com.sankuai.xm.integration.knb.handler.JoinSessionJsHandler");
        hashMap.put("dxsdk.getMessageByUUID", "com.sankuai.xm.integration.knb.handler.GetMessageByUUIDJsHandler");
        hashMap.put("dxsdk.getMessages", "com.sankuai.xm.integration.knb.handler.GetMessagesJsHandler");
        hashMap.put("dxsdk.getMyDXUid", "com.sankuai.xm.integration.knb.handler.GetMyUidJsHandler");
        hashMap.put("dxsdk.getSession", "com.sankuai.xm.integration.knb.handler.GetSessionJsHandler");
        hashMap.put("dxsdk.getSessionList", "com.sankuai.xm.integration.knb.handler.GetSessionsJsHandler");
        hashMap.put("dxsdk.getSessionListUnreadCount", "com.sankuai.xm.integration.knb.handler.GetUnreadCountJsHandler");
        hashMap.put("dxsdk.getSpecialTags", "com.sankuai.xm.integration.knb.handler.GetSessionByTagJsHandler");
        hashMap.put("dxsdk.getVcard", "com.sankuai.xm.integration.knb.handler.GetVCardJsHandler");
        hashMap.put("dxsdk.getVcards", "com.sankuai.xm.integration.knb.handler.GetVCardsJsHandler");
        hashMap.put("dxsdk.init", "com.sankuai.xm.integration.knb.handler.IMInitJsHandler");
        hashMap.put("dxsdk.insertLocalMessage", "com.sankuai.xm.integration.knb.handler.InsertLocalMsgJsHandler");
        hashMap.put("dxsdk.isDXSDKLogin", "com.sankuai.xm.integration.knb.handler.IsLoginJsHandler");
        hashMap.put("dxsdk.isSupportGroupOpposite", "com.sankuai.xm.integration.knb.handler.SupportGroupOppositeJsHandler");
        hashMap.put("dxsdk.isSupportPersonOpposite", "com.sankuai.xm.integration.knb.handler.SupportPersonOppositeJsHandler");
        hashMap.put("dxsdk.isSupportPubOpposite", "com.sankuai.xm.integration.knb.handler.SupportPubOppositeJsHandler");
        hashMap.put("dxsdk.leaveSession", "com.sankuai.xm.integration.knb.handler.LeaveSessionJsHandler");
        hashMap.put("dxsdk.loginCancel", "com.sankuai.xm.integration.knb.handler.CancelLoginJsHandler");
        hashMap.put("dxsdk.loginPassport", "com.sankuai.xm.integration.knb.handler.LoginByPassportJsHandler");
        hashMap.put("dxsdk.loginUid", "com.sankuai.xm.integration.knb.handler.LoginByUidJsHandler");
        hashMap.put("dxsdk.logout", "com.sankuai.xm.integration.knb.handler.LogoffJsHandler");
        hashMap.put("dxsdk.openDXSDKEvent", "com.sankuai.xm.integration.knb.handler.OpenDXSDKEventJsHandler");
        hashMap.put("dxsdk.playVoice", "com.sankuai.xm.integration.knb.handler.PlayVoiceJsHandler");
        hashMap.put("dxsdk.queryGroupOpposite", "com.sankuai.xm.integration.knb.handler.QueryGroupOppositeJsHandler");
        hashMap.put("dxsdk.queryMsgAddition", "com.sankuai.xm.integration.knb.handler.QueryMsgAdditionJsHandler");
        hashMap.put("dxsdk.queryPersonOpposite", "com.sankuai.xm.integration.knb.handler.QueryPersonOppositeJsHandler");
        hashMap.put("dxsdk.queryPubOpposite", "com.sankuai.xm.integration.knb.handler.QueryPubOppositeJsHandler");
        hashMap.put("dxsdk.readSession", "com.sankuai.xm.integration.knb.handler.ReadSessionJsHandler");
        hashMap.put("dxsdk.recordAmplitude", "com.sankuai.xm.integration.knb.handler.GetAudioAmplitudeJsHandler");
        hashMap.put("dxsdk.recordDuration", "com.sankuai.xm.integration.knb.handler.AudioMaxDurationJsHandler");
        hashMap.put("dxsdk.registerDXSDKEvent", "com.sankuai.xm.integration.knb.handler.RegisterEventJsHandler");
        hashMap.put("dxsdk.resendMessage", "com.sankuai.xm.integration.knb.handler.ResendMessageJsHandler");
        hashMap.put("dxsdk.saveFilePath", "com.sankuai.xm.integration.knb.handler.GetMediaFileSavePathJsHandler");
        hashMap.put("dxsdk.saveFolderDir", "com.sankuai.xm.integration.knb.handler.GetMediaFolderJsHandler");
        hashMap.put("dxsdk.sendGroupOpposite", "com.sankuai.xm.integration.knb.handler.SendGroupOppositeJsHandler");
        hashMap.put("dxsdk.sendMessage", "com.sankuai.xm.integration.knb.handler.SendMessageJsHandler");
        hashMap.put("dxsdk.sendPersonOpposite", "com.sankuai.xm.integration.knb.handler.SendPersonOppositeJsHandler");
        hashMap.put("dxsdk.sendPubOpposite", "com.sankuai.xm.integration.knb.handler.SendPubOppositeJsHandler");
        hashMap.put("dxsdk.setAllowBackgroundLogin", "com.sankuai.xm.integration.knb.handler.AllowBackgroundLoginJsHandler");
        hashMap.put("dxsdk.startAudioRecord", "com.sankuai.xm.integration.knb.handler.StartRecordVoiceJsHandler");
        hashMap.put("dxsdk.stopAudioRecord", "com.sankuai.xm.integration.knb.handler.StopRecordVoiceJsHandler");
        hashMap.put("dxsdk.stopPlayVoice", "com.sankuai.xm.integration.knb.handler.StopPlayVoiceJsHandler");
        hashMap.put("dxsdk.unregisterDXSDKEvent", "com.sankuai.xm.integration.knb.handler.UnregisterEventJsHandler");
        hashMap.put("dxsdk.updateLocalMessage", "com.sankuai.xm.integration.knb.handler.UpdateLocalMsgJsHandler");
        hashMap.put("dxsdk.uriToMediaPath", "com.sankuai.xm.integration.knb.handler.UriToMediaPath");
        hashMap.put("ffp.addCustomTags", "com.meituan.android.common.weaver.impl.knb.FFPCustomTags");
        hashMap.put("ffp.record", "com.meituan.android.common.weaver.impl.knb.FFPJsHandlerO");
        hashMap.put("location.getLocationFingerprint", "com.meituan.android.common.locate.util.LocationFingerprintJsHandler");
        hashMap.put("meituan.bindQQ", "com.meituan.passport.oauthlogin.jsbridge.QQBindJSHandler");
        hashMap.put("meituan.bindWechat", "com.meituan.passport.oauthlogin.jsbridge.WechatBindJSHandler");
        hashMap.put("meituan.changeUserWithDeleUser", "com.meituan.passport.changeuser.DeleteUserJSHandler");
        hashMap.put("meituan.changeUserWithGetList", "com.meituan.passport.changeuser.GetUserListJSHandler");
        hashMap.put("meituan.changeUserWithLogin", "com.meituan.passport.changeuser.UserLoginJSHandler");
        hashMap.put("meituan.getUIConfig", "com.meituan.passport.jsbridge.UIConfigJSHandler");
        hashMap.put("meituan.getWXCode", "com.meituan.passport.oauthlogin.jsbridge.WechatBaseDataJSHandler");
        hashMap.put("meituan.loginByWechat", "com.meituan.passport.oauthlogin.jsbridge.WechatLoginJSHandler");
        hashMap.put("meituan.updateUserInfo", "com.meituan.passport.jsbridge.UpdateUserInfo");
        hashMap.put("mlive.dismissMLiveFloat", "com.dianping.live.knb.DismissMLiveFloatJsHandler");
        hashMap.put("mlive.dismissMLiveStatusWidget", "com.dianping.live.knb.DismissMLiveStatusWidgetJsHandler");
        hashMap.put("mlive.showMLiveStatusWidget", "com.dianping.live.knb.ShowMLiveStatusWidgetJsHandler");
        hashMap.put("pike.addAlias", "com.dianping.sdk.pike.knb.AddAliasJsHandler");
        hashMap.put("pike.addTunnelStateListener", "com.dianping.sdk.pike.knb.AddTunnelStateListenerJsHandler");
        hashMap.put("pike.aggAuthenticate", "com.dianping.sdk.pike.knb.AuthAggClientJsHandler");
        hashMap.put("pike.authenticate", "com.dianping.sdk.pike.knb.AuthClientJsHandler");
        hashMap.put("pike.bindTag", "com.dianping.sdk.pike.knb.BindTagJsHandler");
        hashMap.put("pike.getTunnelState", "com.dianping.sdk.pike.knb.GetTunnelStateJsHandler");
        hashMap.put("pike.initAggClient", "com.dianping.sdk.pike.knb.InitAggClientJsHandler");
        hashMap.put("pike.initClient", "com.dianping.sdk.pike.knb.InitClientJsHandler");
        hashMap.put("pike.joinAggClient", "com.dianping.sdk.pike.knb.JoinAggClientJsHandler");
        hashMap.put("pike.leaveAggClient", "com.dianping.sdk.pike.knb.LeaveAggClientJsHandler");
        hashMap.put("pike.releaseAggClient", "com.dianping.sdk.pike.knb.ReleaseAggClientJsHandler");
        hashMap.put("pike.releaseClient", "com.dianping.sdk.pike.knb.ReleaseClientJsHandler");
        hashMap.put("pike.removeAlias", "com.dianping.sdk.pike.knb.RemoveAliasJsHandler");
        hashMap.put("pike.removeTunnelStateListener", "com.dianping.sdk.pike.knb.RemoveTunnelStateListenerJsHandler");
        hashMap.put("pike.sendAggMessage", "com.dianping.sdk.pike.knb.SendAggMessageJsHandler");
        hashMap.put("pike.sendMessage", "com.dianping.sdk.pike.knb.SendMessageJsHandler");
        hashMap.put("pike.startClient", "com.dianping.sdk.pike.knb.StartClientJsHandler");
        hashMap.put("pike.stopClient", "com.dianping.sdk.pike.knb.StopClientJsHandler");
        hashMap.put("pike.unbindTag", "com.dianping.sdk.pike.knb.UnbindTagJsHandler");
        hashMap.put("privacy.getHistories", "com.meituan.android.privacy.histories.PrivacyHistoriesJsHandler");
        hashMap.put(KnbConstants.METHOD_STOP, "com.meituan.ai.speech.sdk.knb.JsStopRecogHandler");
        hashMap.put(KnbConstants.METHOD_SDK_INFO, "com.meituan.ai.speech.sdk.knb.JsSDKInfoHandler");
        hashMap.put(KnbConstants.METHOD_INIT, "com.meituan.ai.speech.sdk.knb.JsInitSpeechRecognizerHandler");
        hashMap.put(KnbConstants.METHOD_START, "com.meituan.ai.speech.sdk.knb.JsStartRecogHandler");
        hashMap.put("uuid.getoaid", "com.meituan.android.common.unionid.oneid.OaidJsHandler");
        hashMap.put("waimai.AccountImageUpload", "com.sankuai.waimai.bussiness.order.list.knb.AccountImageUpload");
        hashMap.put("waimai.checkUpdate", "com.sankuai.waimai.business.page.common.bridge.checkUpdate");
        hashMap.put("waimai.clearCache", "com.sankuai.waimai.bussiness.order.list.knb.ClearAppCache");
        hashMap.put("waimai.customRecommendUserSetOptions", "com.sankuai.waimai.business.page.common.bridge.customRecommendUserSetOptions");
        hashMap.put("waimai.djEncryptRiskData", "com.sankuai.waimai.business.knb.bridge.DJEncryptRiskData");
        hashMap.put("waimai.getAppModel", "com.sankuai.waimai.bussiness.order.list.knb.GetAppModel");
        hashMap.put("waimai.getCacheSize", "com.sankuai.waimai.bussiness.order.list.knb.GetAppCacheSize");
        hashMap.put("waimai.getGBCityInfo", "com.sankuai.waimai.business.knb.bridge.GetGBCityInfoBridge");
        hashMap.put("waimai.getImCount", "com.sankuai.waimai.bussiness.order.list.knb.GetImUnReadCount");
        hashMap.put("waimai.getLocationCoordinate", "com.sankuai.waimai.business.knb.bridge.GetLocationCoordinate");
        hashMap.put("waimai.getMTCityInfo", "com.sankuai.waimai.business.knb.bridge.GetMTCityInfoBridge");
        hashMap.put("waimai.getOrderedGoodCount", "com.sankuai.waimai.bussiness.order.list.knb.GetOrderedGoodCount");
        hashMap.put("waimai.getUnpl", "com.sankuai.waimai.business.knb.handlers.GetUnplHandler");
        hashMap.put("waimai.getWMPoiAddress", "com.sankuai.waimai.business.knb.bridge.GetWMPoiAddress");
        hashMap.put("waimai.handleAutoUpdateState", "com.sankuai.waimai.bussiness.order.list.knb.HandleAutoUpdateState");
        hashMap.put("waimai.handlerOrderSchema", "com.sankuai.waimai.bussiness.order.list.knb.OrderSchemaKNBHandler");
        hashMap.put("waimai.mscPreload", "com.sankuai.waimai.business.knb.bridge.MSCPreload");
        hashMap.put("waimai.openLocation", "com.sankuai.waimai.business.page.common.bridge.OpenLocation");
        hashMap.put("waimai.recordDeepLinkBizInfo", "com.sankuai.waimai.business.knb.bridge.RecordDeepLinkBizInfo");
        hashMap.put("waimai.saveAppModel", "com.sankuai.waimai.bussiness.order.list.knb.SaveAppModel");
        hashMap.put("waimai.setUnpl", "com.sankuai.waimai.business.knb.handlers.SetUnplHandler");
        hashMap.put("waimai.shareApp", "com.sankuai.waimai.business.page.common.bridge.shareApp");
        hashMap.put("waimai.sharePassword", "com.sankuai.waimai.business.knb.handlers.SharePasswordJsHandler");
        hashMap.put("waimai.startDiagnose", "com.sankuai.waimai.business.page.common.bridge.startDiagnose");
        hashMap.put("waimai.updateUserInfo", "com.sankuai.waimai.bussiness.order.list.knb.UpdateUserInfo");
        hashMap.put("waimai.uploadImages", "com.sankuai.waimai.bussiness.order.list.knb.UploadImages");
        hashMap.put("waimai.waimaiPayForWMVIP", "com.sankuai.waimai.business.knb.handlers.PayForWMVIPHandler");
        hashMap.put("yoda.getSensorData", "com.meituan.android.yoda.bridge.knb.GetSensorDataJsHandler");
        hashMap.put("yoda.resizeDialogVerifySize", "com.meituan.android.yoda.bridge.knb.PopWindowResizeJsHandler");
        hashMap.put("yoda.startPickSensorData", "com.meituan.android.yoda.bridge.knb.StartPickSensorDataJsHandler");
        hashMap.put("yoda.stopPickSensorData", "com.meituan.android.yoda.bridge.knb.StopPickSensorDataJsHandler");
        hashMap.put("yoda.useMobileNetRequest", "com.meituan.android.yoda.bridge.knb.UseMobileNetRequestJsHandler");
        hashMap.put("yoda.yodaInfo", "com.meituan.android.yoda.bridge.knb.YodaInfoJsHandler");
        c.put("com.dianping.titans.js.jshandler.BaseJsHandler", hashMap);
        HashMap hashMap2 = new HashMap(14);
        hashMap2.put("hybrid_pre_guide_cashier", "com.meituan.android.cashier.preguide.PreGuideCashier");
        hashMap2.put("hybrid_preposed_mtcashier", "com.meituan.android.cashier.mtpay.HybridPrePosedMTCashierAdapter");
        hashMap2.put("hybrid_standard_cashier", "com.meituan.android.cashier.hybridwrapper.HybridStandardCashierAdapter");
        hashMap2.put("meituanpay_component", "com.meituan.android.cashier.mtpay.MeituanPayComponentCashierAdapter");
        hashMap2.put("native_elderly_cashier", "com.meituan.android.elderly.elderly.ElderlyCashier");
        hashMap2.put("native_standard_cashier", "com.meituan.android.cashier.NativeStandardCashierAdapter");
        hashMap2.put("oneclickpay", "com.meituan.android.cashier.oneclick.OneClickCashier");
        hashMap2.put("pay_defer_sign", "com.meituan.android.cashier.preguide.PayDeferSignCashier");
        hashMap2.put("web_cashier", "com.meituan.android.cashier.web.WebCashierAdapter");
        hashMap2.put("weekpay", "com.meituan.android.cashier.mtpay.WeekPayCashierAdapter");
        c.put("com.meituan.android.cashier.common.ICashier", hashMap2);
        HashMap hashMap3 = new HashMap(3);
        hashMap3.put("logan", "com.dianping.networklog.LoganCIPSBusinessCleaner");
        hashMap3.put("map_sdk", "com.sankuai.meituan.mapfoundation.storage.StorageCleaner");
        c.put("com.meituan.android.cipstorage.CIPSBusinessCleaner", hashMap3);
        HashMap hashMap4 = new HashMap(2);
        hashMap4.put("light_blue", "com.meituan.android.common.aidata.lightblue.LightBlueImpl");
        c.put("com.meituan.android.common.aidata.lightblue.ILightBlue", hashMap4);
        HashMap hashMap5 = new HashMap(2);
        hashMap5.put("ffp.knb.o", "com.meituan.android.common.weaver.impl.knb.KNBBlankPluginO");
        c.put("com.meituan.android.common.weaver.interfaces.blank.IKNBBlankPluginO", hashMap5);
        HashMap hashMap6 = new HashMap(2);
        hashMap6.put("ffp", "com.meituan.android.common.weaver.impl.utils.FFPTopPageImpl");
        c.put("com.meituan.android.common.weaver.interfaces.ffp.IFFPTopPage", hashMap6);
        HashMap hashMap7 = new HashMap(2);
        hashMap7.put("ConfigInit", "com.meituan.android.httpdns.business.ConfigInitImpl");
        c.put("com.meituan.android.httpdns.IConfigInit", hashMap7);
        HashMap hashMap8 = new HashMap(2);
        hashMap8.put("DnsListener", "com.meituan.android.httpdns.business.DefaultDnsListener");
        c.put("com.meituan.android.httpdns.IDnsListener", hashMap8);
        HashMap hashMap9 = new HashMap(10);
        hashMap9.put("MLive", "com.dianping.live.live.mrn.MLivePackageBuilder");
        hashMap9.put("MRNShortVideo", "com.sankuai.meituan.shortvideocore.mrn.MRNShortVideoPackageBuilder");
        hashMap9.put("effect-view", "com.sankuai.waimai.irmo.render.mrn.MrnEffectViewPackageBuilder");
        hashMap9.put("eh_package", "com.meituan.android.qianbao.mmpwidget2rn.rn.QBRNPackageBuilder");
        hashMap9.put("mrn-module", "com.dianping.gcmrnmodule.MRNModulePackageBuilder");
        hashMap9.put("reactX_rn_builder", "com.sankuai.wme.react.x.ReactXBuilder");
        hashMap9.put("rocks-page", "com.sankuai.waimai.rocks.rn.RocksPackageBuilder");
        c.put("com.meituan.android.mrn.IMRNPackageBuilder", hashMap9);
        HashMap hashMap10 = new HashMap(11);
        hashMap10.put(Constants.SDK_LOG_TAG, "com.meituan.android.common.aidata.mrn.RNAIDataConfigProvider");
        hashMap10.put("drug_config", "com.sankuai.waimai.store.drug.mrn.bridge.DrugMRNCommonConfigProvider");
        hashMap10.put("legwork_common", "com.meituan.android.legwork.mrn.reactPackage.LWMRNConfigProvider");
        hashMap10.put("legwork_wm", "com.meituan.android.legwork.mrn.reactPackage.LWMRNWMConfigProvider");
        hashMap10.put("rnstastics", "com.meituan.android.common.mrn.analytics.library.RNStasticsConfigProvider");
        hashMap10.put("sg_config", "com.sankuai.waimai.store.mrn.SGMRNCommonConfigProvider");
        hashMap10.put("sgc_config", "com.sankuai.waimai.store.mrn.SGMRNSgcConfigProvider");
        hashMap10.put("waimai_config", "com.sankuai.waimai.reactnative.WMRNCommonConfigProvider");
        c.put("com.meituan.android.mrn.config.IMRNConfigProvider", hashMap10);
        HashMap hashMap11 = new HashMap(2);
        hashMap11.put("sg_mrn_export", "com.sankuai.waimai.store.mrn.SGMRNExportPackage");
        c.put("com.meituan.android.mrn.config.IMRNReactPackage", hashMap11);
        HashMap hashMap12 = new HashMap(2);
        hashMap12.put("legwork", "com.meituan.android.legwork.mrn.interceptor.MRNInterceptor");
        c.put("com.meituan.android.mrn.module.MRNRequestInterceptor", hashMap12);
        HashMap hashMap13 = new HashMap(51);
        hashMap13.put("about-app", "com.sankuai.waimai.business.page.setting.rn.AboutAPPMrnReactPackage");
        hashMap13.put("applyrefund", "com.sankuai.waimai.bussiness.order.list.rn.OrderListMrnReactPackage");
        hashMap13.put("city-delivery", "com.sankuai.waimai.business.page.common.mrn.reactpackages.DeliverCityMrnReactPackage");
        hashMap13.put("content-feed-list", "com.sankuai.waimai.business.page.home.list.feed.rn.UGCMRNReactPackage");
        hashMap13.put("coupon-poilist", "com.sankuai.waimai.business.page.common.mrn.reactpackages.UnavailablePoiListMrnReactPackage");
        hashMap13.put("coupon-select", "com.sankuai.waimai.bussiness.order.confirm.coupon.rn.OrderConfirmPoiCouponMrnReactPackage");
        hashMap13.put("coupon-unavailable-poilist", "com.sankuai.waimai.business.page.common.mrn.reactpackages.UnavailablePoiListMrnReactPackage");
        hashMap13.put("drug-coupon-select", "com.sankuai.waimai.bussiness.order.confirm.coupon.rn.DrugOrderConfirmPoiCouponMrnReactPackage");
        hashMap13.put("expired-coupon", "com.sankuai.waimai.bussiness.order.confirm.coupon.rn.OrderConfirmPoiCouponMrnReactPackage");
        hashMap13.put("expired-redpacket", "com.sankuai.waimai.bussiness.order.confirm.coupon.rn.OrderConfirmPoiCouponMrnReactPackage");
        hashMap13.put("expired-redpacket-style2", "com.sankuai.waimai.bussiness.order.confirm.coupon.rn.OrderConfirmPoiCouponMrnReactPackage");
        hashMap13.put("flashbuy-coupon-select", "com.sankuai.waimai.bussiness.order.confirm.coupon.rn.SCOrderConfirmPoiCouponMrnReactPackage");
        hashMap13.put("globalcart", "com.sankuai.waimai.globalcart.rn.GlobalcartReactPackage");
        hashMap13.put("globalcartold", "com.sankuai.waimai.globalcart.rn.GlobalcartReactPackage");
        hashMap13.put("hotel-mlive", "com.dianping.live.live.mrn.MLiveMrnReactPackage");
        hashMap13.put("mine-finish-comment", "com.sankuai.waimai.business.user.comment.rn.UserCommentShareMrnReactPackage");
        hashMap13.put("multi-person", "com.sankuai.waimai.business.restaurant.rn.RestaurantMrnReactPackage");
        hashMap13.put("multi-person-bill", "com.sankuai.waimai.business.restaurant.composeorder.rn.MultiPersonBillMRNReactPackage");
        hashMap13.put("order-comment", "com.sankuai.waimai.bussiness.order.list.rn.OrderListMrnReactPackage");
        hashMap13.put("order-comment-share", "com.sankuai.waimai.business.user.comment.rn.UserCommentShareMrnReactPackage");
        hashMap13.put("order-remark", "com.sankuai.waimai.bussiness.order.confirm.rn.OrderConfirmInvoiceMrnReactPackage");
        hashMap13.put("order-search", "com.sankuai.waimai.bussiness.order.list.rn.OrderListMrnReactPackage");
        hashMap13.put("pay-by-another", "com.sankuai.waimai.bussiness.order.paybyfriend.rn.PayByFriendMrnReactPackage");
        hashMap13.put("person-page", "com.sankuai.waimai.business.page.home.list.feed.rn.UGCMRNReactPackage");
        hashMap13.put("private-menu", "com.sankuai.waimai.business.restaurant.rn.RestaurantMrnReactPackage");
        hashMap13.put("productRank", "com.sankuai.waimai.business.restaurant.rn.RestaurantMrnReactPackage");
        hashMap13.put("refundstatus", "com.sankuai.waimai.bussiness.order.list.rn.OrderListMrnReactPackage");
        hashMap13.put("rocks-page", "com.sankuai.waimai.business.ugc.TodayRecommendFoodMrnReactPackage");
        hashMap13.put("search-guide", "com.sankuai.waimai.business.search.ui.mrn.GuideRnReactPackage");
        hashMap13.put("select-redpacket", "com.sankuai.waimai.bussiness.order.confirm.coupon.rn.OrderConfirmSelectCouponMrnReactPackage");
        hashMap13.put("select-redpacket-new", "com.sankuai.waimai.bussiness.order.confirm.coupon.rn.OrderConfirmSelectCouponMrnReactPackage");
        hashMap13.put("setting-page", "com.sankuai.waimai.business.page.setting.rn.SettingPageMrnReactPackage");
        hashMap13.put("student-center", "com.sankuai.waimai.business.user.rn.studentcenter.StudentCenterMrnReactPackage");
        hashMap13.put("today-eat-what", "com.sankuai.waimai.business.ugc.TodayRecommendFoodMrnReactPackage");
        hashMap13.put("today-recommend-food", "com.sankuai.waimai.business.ugc.TodayRecommendFoodMrnReactPackage");
        hashMap13.put("union-coupon-select", "com.sankuai.waimai.bussiness.order.confirm.coupon.rn.OrderConfirmSelectCouponMrnReactPackage");
        hashMap13.put("wm-order-list", "com.sankuai.waimai.bussiness.order.list.rn.OrderListMrnReactPackage");
        hashMap13.put("wm-search-suggest", "com.sankuai.waimai.business.search.ui.mrn.SuggestRnReactPackage");
        c.put("com.meituan.android.mrn.shell.MRNReactPackageInterface", hashMap13);
        HashMap hashMap14 = new HashMap(10);
        hashMap14.put("pay_getBiometricsInfo", "com.meituan.android.pay.bridge.GetBiometricParamsBridge");
        hashMap14.put("pay_hybridMtpCashierTransferProcess", "com.meituan.android.pay.bridge.HybridMeituanPayBridge");
        hashMap14.put("pay_notifyHybridProcessResult", "com.meituan.android.hybridcashier.bridge.result.NotifyHybridProcessResultHandler");
        hashMap14.put("pay_verifyBiometricInfo", "com.meituan.android.pay.bridge.VerifyBiometricInfoBridge");
        hashMap14.put("signPay_closePage", "com.meituan.android.pay.bridge.SignPayClosePageBridge");
        hashMap14.put("signPay_modal", "com.meituan.android.pay.bridge.SignPayModalBridge");
        hashMap14.put("signPay_signPayResult", "com.meituan.android.pay.bridge.SignPayResultBridge");
        c.put("com.meituan.android.neohybrid.neo.bridge.handler.NeoBridgeCustomizeInterface", hashMap14);
        HashMap hashMap15 = new HashMap(34);
        hashMap15.put("pay.callMeituanPay", "com.meituan.android.pay.jshandler.OpenPayActivityJsHandler");
        hashMap15.put("pay.callThirdPay", "com.meituan.android.cashier.bridge.CallThirdPayJsHandler");
        hashMap15.put("pay.cashierAvailable", "com.meituan.android.cashier.common.CashierAvailableJsHandler");
        hashMap15.put("pay.cashierRepeatCount", "com.meituan.android.cashier.bridge.CashierRepeatCountJSHandler");
        hashMap15.put("pay.cashierSnapShot", "com.meituan.android.paycommon.lib.webview.jshandler.CashierScreenSnapShotJsHandler");
        hashMap15.put("pay.getMeituanPayParams", "com.meituan.android.pay.jshandler.GetMeituanPayParamsJSHandler");
        hashMap15.put("pay.getPayCommonParam", "com.meituan.android.pay.jshandler.GetPayCommonParamJSHandler");
        hashMap15.put("pay.getUpsePayType", "com.meituan.android.cashier.bridge.GetUpsePayTypeJsHandler");
        hashMap15.put("pay.hybridMeituanPay", "com.meituan.android.pay.jshandler.HybridSignPayJSHandler");
        hashMap15.put("pay.hybridMtpCashierTransferProcess", "com.meituan.android.pay.jshandler.HybridMeituanPayJSHandler");
        hashMap15.put("pay.identifyIdCard", "com.meituan.android.identifycardrecognizer.jshandler.IdCardOcrJSHandler");
        hashMap15.put("pay.identifyIdCardProcess", "com.meituan.android.identifycardrecognizer.jshandler.IdCardOcrProcessJSHandler");
        hashMap15.put("pay.openAlipayNoPassword", "com.meituan.android.paymentchannel.bridge.OpenAlipayNoPassword");
        hashMap15.put("pay.openHalfPage", "com.meituan.android.paycommon.lib.webview.jshandler.OpenHalfPageJsHandler");
        hashMap15.put("pay.openOneClickPay", "com.meituan.android.cashier.oneclick.jshandler.OpenOneClickPayJsHandler");
        hashMap15.put("pay.openScanBankCardCamera", "com.meituan.android.ocr.OpenCameraJsHandler");
        hashMap15.put("pay.openWeixinNoPassword", "com.meituan.android.paymentchannel.bridge.OpenWechatNoPswJsHandler");
        hashMap15.put("pay.openWeixinScorePay", "com.meituan.android.paymentchannel.bridge.OpenWeixinScorePay");
        hashMap15.put("pay.screenshotControl", "com.meituan.android.paycommon.lib.webview.jshandler.ScreenshotControlJsHandler");
        hashMap15.put("pay.selectBank", "com.meituan.android.cashier.bridge.icashier.ICashierJSHandler");
        hashMap15.put("pay.setMeituanPayResult", "com.meituan.android.pay.jshandler.SetMeituanPayResultJSHandler");
        hashMap15.put("pay.showCouponDialog", "com.meituan.android.pay.jshandler.CouponDialogJsHandler");
        hashMap15.put("pay.startCertificate", "com.meituan.android.identifycardrecognizer.jshandler.StartCertificateJSHandler");
        hashMap15.put("pay.transferPopUpParams", "com.meituan.android.paycommon.lib.webview.jshandler.HybridCouponDialogJsHandler");
        hashMap15.put("pay.verifyBiometricInfo", "com.meituan.android.pay.jshandler.BiologicalValidationJSHandler");
        c.put("com.meituan.android.paybase.moduleinterface.FinanceJsHandler", hashMap15);
        HashMap hashMap16 = new HashMap(2);
        hashMap16.put("cashier.webview.fragment", "com.meituan.android.paymentchannel.webpay.CashierWebViewWithTitansFragment");
        c.put("com.meituan.android.paybase.moduleinterface.KNBWebViewFragment", hashMap16);
        HashMap hashMap17 = new HashMap(2);
        hashMap17.put("uppayMgeUtils", "com.meituan.android.finthirdpayadapter.utils.UPPayResultMgeUtils");
        c.put("com.meituan.android.paybase.moduleinterface.payment.OnGotUPPayResult", hashMap17);
        HashMap hashMap18 = new HashMap(2);
        hashMap18.put("ThirdPayResultUtils", "com.meituan.android.paymentchannel.utils.ThirdPayResultUtils");
        c.put("com.meituan.android.paybase.moduleinterface.payment.PayActionListener", hashMap18);
        HashMap hashMap19 = new HashMap(5);
        hashMap19.put("unionflashpay", "com.meituan.android.finthirdpayadapter.payer.UPFlashPayer");
        hashMap19.put("upmppay", "com.meituan.android.finthirdpayadapter.payer.UPPayer");
        hashMap19.put("upsepay", "com.meituan.android.finthirdpayadapter.payer.UPSEPayer");
        c.put("com.meituan.android.paybase.moduleinterface.payment.Payer", hashMap19);
        HashMap hashMap20 = new HashMap(2);
        hashMap20.put("UPPayHandle", "com.meituan.android.finthirdpayadapter.payer.UPPayHandle");
        c.put("com.meituan.android.paybase.moduleinterface.payment.UPPayAPI", hashMap20);
        HashMap hashMap21 = new HashMap(2);
        hashMap21.put("onPasswordInsert", "com.meituan.android.pay.activity.ConfirmPasswordCallbackImpl");
        c.put("com.meituan.android.paybase.password.verifypassword.OnPasswordInsertListener", hashMap21);
        HashMap hashMap22 = new HashMap(10);
        hashMap22.put("cashier", "com.meituan.android.cashier.common.CashierInit");
        hashMap22.put("hybridPrePosedMTCashier", "com.meituan.android.cashier.mtpay.HybridPrePosedMTCashierInit");
        hashMap22.put("hybridcashier", "com.meituan.android.cashier.hybridwrapper.HybridCashierInit");
        hashMap22.put("meituan_pay", "com.meituan.android.pay.init.MeituanPayInit");
        hashMap22.put("one_click", "com.meituan.android.cashier.oneclick.hybrid.OneClickInit");
        hashMap22.put("recce_init", "com.meituan.android.wallet.RecceInit");
        hashMap22.put("standardCashier", "com.meituan.android.cashier.StandardCashierInit");
        c.put("com.meituan.android.paycommon.lib.IInitSDK", hashMap22);
        HashMap hashMap23 = new HashMap(2);
        hashMap23.put("wasai_one_click_pay_modal", "com.meituan.android.cashier.oneclick.recce.OneClickPayPackage");
        c.put("com.meituan.android.recce.ReccePackage", hashMap23);
        HashMap hashMap24 = new HashMap(2);
        hashMap24.put("startPassVerify", "com.meituan.android.cashier.oneclick.recce.bridge.StartPassVerifyInterface");
        c.put("com.meituan.android.recce.bridge.RecceCustomApi", hashMap24);
        HashMap hashMap25 = new HashMap(49);
        hashMap25.put("addMapCircles", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("addMapControls", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("addMapLines", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("addMapMarkers", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("addMapPolygons", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put(WMCalendarModule.ADD_PHONE_CALENDAR, "com.meituan.mmp.lib.api.calendar.CalendarModule");
        hashMap25.put("addPhoneRepeatCalendar", "com.meituan.mmp.lib.api.calendar.CalendarModule");
        hashMap25.put("bindWXAccount", "com.meituan.mmp.lib.api.wx.WXAuthInfoApi");
        hashMap25.put("getMapCenterLocation", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("getMapRegion", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("getMapRotate", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("getMapScale", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("getUserStepCount", "com.meituan.mmp.lib.api.step.StepModule");
        hashMap25.put("getWXAuthInfo", "com.meituan.mmp.lib.api.wx.WXAuthInfoApi");
        hashMap25.put("hideKeyboard", "com.meituan.mmp.lib.api.input.InputApi");
        hashMap25.put("includeMapPoints", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("insertInput", "com.meituan.mmp.lib.api.input.InputApi");
        hashMap25.put("insertLivePlayer", "com.meituan.mmp.lib.api.live.LivePlayerApi");
        hashMap25.put("insertLivePusher", "com.meituan.mmp.lib.api.live.push.LivePushApi");
        hashMap25.put("insertMap", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("moveToMapLocation", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("openDocument", "com.meituan.mmp.lib.api.file.DocumentModule");
        hashMap25.put("operateLivePlayer", "com.meituan.mmp.lib.api.live.LivePlayerApi");
        hashMap25.put("operateLivePusher", "com.meituan.mmp.lib.api.live.push.LivePushApi");
        hashMap25.put("removeInput", "com.meituan.mmp.lib.api.input.InputApi");
        hashMap25.put("removeLivePlayer", "com.meituan.mmp.lib.api.live.LivePlayerApi");
        hashMap25.put("removeLivePusher", "com.meituan.mmp.lib.api.live.push.LivePushApi");
        hashMap25.put("removeMap", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("removeMapMarkers", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("setMapCenterOffset", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("setMapLocMarkerIcon", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("translateMapMarker", "com.meituan.mmp.lib.map.MapApi");
        hashMap25.put("updateInput", "com.meituan.mmp.lib.api.input.InputApi");
        hashMap25.put("updateLivePlayer", "com.meituan.mmp.lib.api.live.LivePlayerApi");
        hashMap25.put("updateLivePusher", "com.meituan.mmp.lib.api.live.push.LivePushApi");
        hashMap25.put("updateMap", "com.meituan.mmp.lib.map.MapApi");
        c.put("com.meituan.mmp.lib.api.ActivityApi", hashMap25);
        HashMap hashMap26 = new HashMap(11);
        hashMap26.put("getAccountInfoSync", "com.meituan.mmp.lib.api.info.AppInfoModule");
        hashMap26.put("getBatteryInfo", "com.meituan.mmp.lib.api.device.BatteryModule");
        hashMap26.put("getBatteryInfoSync", "com.meituan.mmp.lib.api.device.BatteryModule");
        hashMap26.put("getClipboardData", "com.meituan.mmp.lib.api.device.ClipboardModule");
        hashMap26.put("makePhoneCall", "com.meituan.mmp.lib.api.device.PhoneCallModule");
        hashMap26.put("setClipboardData", "com.meituan.mmp.lib.api.device.ClipboardModule");
        hashMap26.put("vibrateLong", "com.meituan.mmp.lib.api.device.VibrateModule");
        hashMap26.put("vibrateShort", "com.meituan.mmp.lib.api.device.VibrateModule");
        c.put("com.meituan.mmp.lib.api.ServiceApi", hashMap26);
        HashMap hashMap27 = new HashMap(2);
        hashMap27.put("mmp_external_auth_provider", "com.meituan.mmp.lib.api.auth.ExternalAuthProvider");
        c.put("com.meituan.mmp.lib.api.auth.IExternalAuthProvider", hashMap27);
        HashMap hashMap28 = new HashMap(11);
        hashMap28.put("Alita_LX", "com.meituan.mmp.lib.api.report.AlitaLxApi");
        hashMap28.put("privateAPI_collectPoi", "com.sankuai.waimai.store.drug.mmp.apis.CollectPoiApi");
        hashMap28.put("privateAPI_getNativeShopCartData", "com.sankuai.waimai.store.drug.mmp.apis.GetNativeShopCartDataApi");
        hashMap28.put("privateAPI_getShopCartData", "com.sankuai.waimai.store.drug.mmp.apis.GetShopCartDataApi");
        hashMap28.put("privateAPI_jumpToPoiChatPage", "com.sankuai.waimai.store.drug.mmp.apis.JumpToPoiChatPageApi");
        hashMap28.put("privateAPI_purchaseNow", "com.sankuai.waimai.store.drug.mmp.apis.PurchaseNowApi");
        hashMap28.put("privateAPI_submitOrder", "com.sankuai.waimai.store.drug.mmp.apis.SubmitOrderApi");
        hashMap28.put("privateAPI_updateNativeShopCartData", "com.sankuai.waimai.store.drug.mmp.apis.UpdateNativeShopCartDataApi");
        c.put("com.meituan.mmp.lib.api.extension.ExtensionPrivateApiFactory", hashMap28);
        HashMap hashMap29 = new HashMap(2);
        hashMap29.put("mmp_x5_provider", "com.meituan.mmp.lib.web.X5Provider");
        c.put("com.meituan.mmp.lib.web.IX5Provider", hashMap29);
        HashMap hashMap30 = new HashMap(2);
        hashMap30.put("mp_white_screen_check_reporter", "com.meituan.android.common.weaver.impl.msc.BlankListener");
        c.put("com.meituan.msc.common.lib.IWhiteScreenCheckReporter", hashMap30);
        HashMap hashMap31 = new HashMap(2);
        hashMap31.put("msc_navigation_start_time_reporter", "com.meituan.android.common.weaver.impl.msc.MSCRouteListener");
        c.put("com.meituan.msc.lib.interfaces.IMSCNavigationReporter", hashMap31);
        HashMap hashMap32 = new HashMap(3);
        hashMap32.put("61cbdaae3b504b9b", "com.sankuai.waimai.store.drug.msc.preload.DrugMSCPreloadRequestImpl");
        hashMap32.put("7122f6e193de47c1", "com.sankuai.waimai.store.SGMSCPreRequestImpl");
        c.put("com.meituan.msc.lib.interfaces.IRequestPrefetchListener", hashMap32);
        HashMap hashMap33 = new HashMap(2);
        hashMap33.put("7122f6e193de47c1", "com.sankuai.waimai.store.goods.list.viewblocks.pagenotfound.PageNotFoundManager");
        c.put("com.meituan.msc.lib.interfaces.PageNotFoundCallback", hashMap33);
        HashMap hashMap34 = new HashMap(2);
        hashMap34.put("msc_location_loader_creator", "com.meituan.msc.modules.api.location.MSCLocationLoader");
        c.put("com.meituan.msc.modules.api.location.MSCLocationLoaderCreator", hashMap34);
        HashMap hashMap35 = new HashMap((int) TbsListener.ErrorCode.STARTDOWNLOAD_2);
        hashMap35.put("FileSystemManager", "com.meituan.msi.api.file.FileApi");
        hashMap35.put("GetCommonParamImpl", "com.sankuai.waimai.store.drug.mmp.apis.GetCommonParamImpl");
        hashMap35.put("GetImChatUnReadNumberImpl", "com.sankuai.waimai.store.drug.mmp.apis.GetImChatUnReadNumberImpl");
        hashMap35.put("Record", "com.meituan.msi.api.record.RecordApi");
        hashMap35.put("ShopCartApiImpl", "com.sankuai.waimai.store.drug.mmp.apis.ShopCartApiImpl");
        hashMap35.put("SwitchHomeTabBarByIndexImpl", "com.sankuai.waimai.store.drug.mmp.apis.SwitchHomeTabBarByIndexImpl");
        hashMap35.put("accelerometer", "com.meituan.msi.api.accelerometer.AccelerometerApi");
        hashMap35.put("actionsheet", "com.meituan.msi.api.dialog.ActionSheetApi");
        hashMap35.put("addPhoneContact", "com.meituan.msi.api.contact.AddPhoneContactApi");
        hashMap35.put(GearsLocator.ADDRESS, "com.meituan.msi.api.address.ChooseAddress");
        hashMap35.put(AlitaMonitorCenter.AlitaExceptionMonitorConst.BUSINESS, "com.meituan.msi.api.Alita.AlitaApi");
        hashMap35.put("audio", "com.meituan.msi.api.audio.AudioApi");
        hashMap35.put("authorize", "com.meituan.msi.api.authorize.AuthorizeApi");
        hashMap35.put("batteryinfo", "com.meituan.msi.api.batteryinfo.GetBatteryInfoApi");
        hashMap35.put("calendar", "com.meituan.msi.api.calendar.CalendarApi");
        hashMap35.put("canIUse", "com.meituan.msi.api.caniuse.CanIUseApi");
        hashMap35.put("captureScreen", "com.meituan.msi.api.capturescreen.CaptureScreenApi");
        hashMap35.put("chooseContact", "com.meituan.msi.api.contact.ChooseContactApi");
        hashMap35.put("clipboard", "com.meituan.msi.api.clipboard.ClipboardApi");
        hashMap35.put("compass", "com.meituan.msi.api.compass.CompassApi");
        hashMap35.put("component_canvas", "com.meituan.msi.api.component.canvas.MsiCanvasViewApi");
        hashMap35.put("component_video", "com.meituan.msi.api.component.video.VideoPlayerApi");
        hashMap35.put("component_video_bridge", "com.meituan.msi.api.component.video.MsiVideoBridge");
        hashMap35.put("customSampling", "com.meituan.msi.api.report.CustomSamplingApi");
        hashMap35.put("devicemotion", "com.meituan.msi.api.devicemotion.DeviceMotionApi");
        hashMap35.put("download", "com.meituan.msi.api.download.DownloadApi");
        hashMap35.put("download_new", "com.sankuai.meituan.kernel.net.msi.DownloadApi");
        hashMap35.put("floatView", "com.dianping.live.live.floatBridge.FloatViewBridgeImpl");
        hashMap35.put("fspRecord", "com.meituan.android.common.weaver.impl.msi.MSIBridge");
        hashMap35.put("getDrugPoiData", "com.sankuai.waimai.store.drug.mmp.apis.GetDrugPoiDataImpl");
        hashMap35.put("getRequestNativeCommonParam", "com.sankuai.waimai.store.drug.mmp.apis.CouponChangeStateImpl");
        hashMap35.put("gyroscope", "com.meituan.msi.api.gyroscope.GyroscopeApi");
        hashMap35.put("horn", "com.meituan.android.common.horn.msi.HornMSIBridge");
        hashMap35.put("image", "com.meituan.msi.api.image.ImageApi");
        hashMap35.put("intoRestaurantPreproceImpl", "com.sankuai.waimai.store.drug.mmp.apis.IntoRestaurantPreproceImpl");
        hashMap35.put("jumptolink", "com.meituan.msi.api.router.JumpToLink");
        hashMap35.put("location", "com.meituan.msi.api.location.LocationApi");
        hashMap35.put("logan", "com.meituan.msi.api.Logan.LoganAPI");
        hashMap35.put("lx", "com.meituan.lx.MsiLx");
        hashMap35.put("mapComponent", "com.meituan.msi.lib.map.api.BaseMapApi");
        hashMap35.put("media", "com.meituan.msi.api.video.MediaAPI");
        hashMap35.put("medicinePay", "com.sankuai.waimai.store.drug.mmp.apis.MedicinePayImpl");
        hashMap35.put("mmpRouteMapping", "com.meituan.mmp.lib.config.RouteMappingModule");
        hashMap35.put(UIConfig.MODAL, "com.meituan.msi.api.dialog.ModalApi");
        hashMap35.put("msc_FileProtocolApi", "com.meituan.msc.modules.api.msi.api.FileApi");
        hashMap35.put("msc_appInfo", "com.meituan.msc.modules.api.msi.api.AppInfoApi");
        hashMap35.put("msc_background", "com.meituan.msc.modules.api.msi.api.BackgroundApi");
        hashMap35.put("msc_component_cover_image_view", "com.meituan.msc.modules.api.msi.components.CoverImageApi");
        hashMap35.put("msc_component_cover_scroll_view", "com.meituan.msc.modules.api.msi.components.CoverScrollViewApi");
        hashMap35.put("msc_component_cover_view", "com.meituan.msc.modules.api.msi.components.CoverTextViewApi");
        hashMap35.put("msc_component_web_view", "com.meituan.msc.modules.api.msi.webview.WebViewComponentApi");
        hashMap35.put("msc_initialCache", "com.meituan.msc.modules.api.msi.api.InitialCacheApi");
        hashMap35.put("msc_keyboardApi", "com.meituan.msc.modules.api.msi.api.KeyboardApi");
        hashMap35.put("msc_menu_button", "com.meituan.msc.modules.api.MenuButton.MenuButtonApi");
        hashMap35.put("msc_miniprogram", "com.meituan.msc.modules.api.msi.navigation.MiniProgramApi");
        hashMap35.put("msc_navigation", "com.meituan.msc.modules.api.msi.navigation.NavigationApi");
        hashMap35.put("msc_navigation_bar", "com.meituan.msc.modules.api.msi.api.NavigationBarApi");
        hashMap35.put("msc_pageApi", "com.meituan.msc.modules.api.msi.api.BeforeUnloadApi");
        hashMap35.put("msc_pageScrollTo", "com.meituan.msc.modules.api.msi.api.ui.PageScrollApi");
        hashMap35.put("msc_pullDownRefresh", "com.meituan.msc.modules.api.msi.api.PullDownRefreshApi");
        hashMap35.put("msc_reportBizTagsApi", "com.meituan.msc.modules.api.msi.api.ReportBizTagsApi");
        hashMap35.put("msc_requestPrefetch", "com.meituan.msc.modules.api.network.RequestPrefetchApi");
        hashMap35.put("msc_sharemenu", "com.meituan.msc.modules.api.msi.api.ShareMenuApi");
        hashMap35.put("msc_tabbar", "com.meituan.msc.modules.api.msi.tabbar.TabBarApi");
        hashMap35.put("msc_updateManagerApi", "com.meituan.msc.modules.api.msi.api.UpdateManagerApi");
        hashMap35.put("msi_component_input", "com.meituan.msi.api.component.input.InputApi");
        hashMap35.put("msi_component_textArea", "com.meituan.msi.api.component.textaera.TextAreaApi");
        hashMap35.put("msi_picker", "com.meituan.msi.api.component.picker.PickerApi");
        hashMap35.put("msi_publish_sub_event", "com.meituan.msi.api.event.PublishSubApi");
        hashMap35.put("network", "com.meituan.msi.api.network.NetworkTypeApi");
        hashMap35.put("phoneCall", "com.meituan.msi.api.phonecall.MakePhoneCallApi");
        hashMap35.put("refreshLocation", "com.sankuai.waimai.business.address.msi.RefreshLocation");
        hashMap35.put("report", "com.meituan.msi.api.report.ReportApi");
        hashMap35.put("reportMsi", "com.meituan.msi.api.report.ReportMSIMetricsApi");
        hashMap35.put(SocialConstants.TYPE_REQUEST, "com.meituan.msi.api.request.RequestApi");
        hashMap35.put("request_new", "com.sankuai.meituan.kernel.net.msi.RequestApi");
        hashMap35.put("schema", "com.meituan.msi.api.schema.OpenLinkApi");
        hashMap35.put(CaptureJsHandler.CAPTURE_TYPE_DEFAULT, "com.meituan.msi.api.screen.ScreenApi");
        hashMap35.put("service", "com.meituan.msi.service.ServiceApi");
        hashMap35.put("setting", "com.meituan.msi.api.setting.SettingApi");
        hashMap35.put("sgc-chat", "com.sankuai.waimai.store.msi.apis.SGIChat");
        hashMap35.put("sgc-chat-new", "com.sankuai.waimai.store.msi.apis.SGIChatNew");
        hashMap35.put("sgc-common", "com.sankuai.waimai.store.msi.apis.SGICommon");
        hashMap35.put("sgc-coupon", "com.sankuai.waimai.store.msi.apis.SGICoupon");
        hashMap35.put("sgc-floatLayer", "com.sankuai.waimai.store.msi.apis.SGIFloatLayer");
        hashMap35.put("sgc-foodOperator", "com.sankuai.waimai.store.msi.apis.SGIFoodOperator");
        hashMap35.put("sgc-message", "com.sankuai.waimai.store.msi.apis.SGIMessage");
        hashMap35.put("sgc-order", "com.sankuai.waimai.store.msi.apis.SGOrder");
        hashMap35.put("sgc-page", "com.sankuai.waimai.store.msi.apis.SGIPage");
        hashMap35.put("sgc-request", "com.sankuai.waimai.store.msi.apis.SGIRequestInfo");
        hashMap35.put("sgc-shopcart", "com.sankuai.waimai.store.msi.apis.SGIShopcart");
        hashMap35.put("sgc-user", "com.sankuai.waimai.store.msi.apis.SGIUser");
        hashMap35.put("sharedStorage", "com.meituan.msi.api.sharedstorage.SharedStorageApi");
        hashMap35.put("storage", "com.meituan.msi.api.storage.StorageApi");
        hashMap35.put("systemInfo", "com.meituan.msi.api.systeminfo.SystemInfoApi");
        hashMap35.put("tabbar", "com.meituan.mmp.lib.msi.tabbar.TabBarApi");
        hashMap35.put("time", "com.meituan.msi.api.time.TimeApi");
        hashMap35.put("toast", "com.meituan.msi.api.toast.ToastApi");
        hashMap35.put("upload", "com.meituan.msi.api.upload.UploadApi");
        hashMap35.put("upload_new", "com.sankuai.meituan.kernel.net.msi.UploadApi");
        hashMap35.put("vibrate", "com.meituan.msi.api.vibrate.VibrateApi");
        hashMap35.put("video", "com.meituan.msi.api.video.VideoApi");
        hashMap35.put("webSocket", "com.meituan.msi.api.websocket.WebSocketApi");
        hashMap35.put("webSocket_new", "com.sankuai.meituan.kernel.net.msi.WebSocketApi");
        hashMap35.put("wifi", "com.meituan.msi.api.wifi.WifiApi");
        hashMap35.put("wm_api_common", "com.sankuai.waimai.platform.net.msi.WMCommonMsiBridge");
        hashMap35.put("wm_check_host", "com.sankuai.waimai.mmp.modules.api.WmCheckHostVersion");
        hashMap35.put("wm_mmp_payment", "com.sankuai.waimai.mmp.modules.api.WmMMPPayment");
        hashMap35.put("wm_msc_payment", "com.sankuai.waimai.mmp.modules.api.WmMSCPayment");
        hashMap35.put("wm_msc_risk_fingerprint", "com.sankuai.waimai.mmp.modules.api.WmRiskControlFingerprint");
        hashMap35.put("wm_msc_select_city", "com.sankuai.waimai.mmp.modules.api.WmSelectedCityInfo");
        hashMap35.put("wm_mt_abtest", "com.sankuai.waimai.mmp.modules.api.ABTestApi");
        hashMap35.put("wm_paymentcommissioncontract", "com.sankuai.waimai.mmp.modules.api.OpenPaymentCommissionContract");
        hashMap35.put("wm_request_api", "com.sankuai.waimai.platform.net.msi.WmRequestApiImpl");
        hashMap35.put("wm_update_host", "com.sankuai.waimai.mmp.modules.api.WmUpdateHost");
        hashMap35.put("wmad-base", "com.sankuai.waimai.ad.msi.WMAdBizAdaptor");
        hashMap35.put("wminvoicetitle", "com.sankuai.waimai.mmp.modules.api.WmChooseInvoiceTitle");
        hashMap35.put("wmmscshare", "com.sankuai.waimai.mmp.modules.api.WMMSIShareApi");
        hashMap35.put("wmmscuser", "com.sankuai.waimai.mmp.modules.api.WMMSIUserApi");
        hashMap35.put("wmopenLocation", "com.sankuai.waimai.mmp.modules.api.WMMSIOpenLocationApi");
        c.put("com.meituan.msi.api.IMsiApi", hashMap35);
        HashMap hashMap36 = new HashMap(6);
        hashMap36.put("MSICanvas", "com.meituan.msi.api.component.canvas.MsiNativeCanvas");
        hashMap36.put("MSIInput", "com.meituan.msi.api.component.input.Input");
        hashMap36.put("MSITextArea", "com.meituan.msi.api.component.textaera.TextArea");
        hashMap36.put("MSIVideo", "com.meituan.msi.api.component.video.MsiNativeVideo");
        c.put("com.meituan.msi.component.IMsiComponent", hashMap36);
        HashMap hashMap37 = new HashMap(2);
        hashMap37.put("mmp_msi_dynamic_config", "com.meituan.mmp.lib.msi.MMPDynamicConfig");
        c.put("com.meituan.msi.context.IContainerDynamicConfig", hashMap37);
        HashMap hashMap38 = new HashMap(3);
        hashMap38.put("onScreenCapture", "com.meituan.msi.module.OnScreenCaptureEvent");
        hashMap38.put("onWindowChanged", "com.meituan.msi.module.OnWindowInfoChangedEvent");
        c.put("com.meituan.msi.module.ApiModule", hashMap38);
        HashMap hashMap39 = new HashMap(2);
        hashMap39.put("passport.check.logout.service", "com.meituan.passport.moduleinterface.CheckLogoutServiceProviderImpl");
        c.put("com.meituan.passport.api.CheckLogoutServiceProvider", hashMap39);
        HashMap hashMap40 = new HashMap(2);
        hashMap40.put("passport.status.debug", "com.meituan.passport.moduleinterface.PassportProviderImpl");
        c.put("com.meituan.passport.api.IPassportProvider", hashMap40);
        HashMap hashMap41 = new HashMap(2);
        hashMap41.put("passport.exchange.report", "com.meituan.passport.moduleinterface.ReportExChangeLoginImpl");
        c.put("com.meituan.passport.api.ReportExChangeLoginProvider", hashMap41);
        HashMap hashMap42 = new HashMap(2);
        hashMap42.put("passport.oauthlogin", "com.meituan.passport.oauthlogin.moduleinterface.OAuthModuleInterface");
        c.put("com.meituan.passport.interfaces.OAuthProvider", hashMap42);
        HashMap hashMap43 = new HashMap(2);
        hashMap43.put("eh_component", "com.sankuai.eh.component.web.wm.EHWMWebComponent");
        c.put("com.sankuai.eh.component.service.spi.IComponent", hashMap43);
        HashMap hashMap44 = new HashMap(2);
        hashMap44.put("component_wm_init", "com.sankuai.eh.component.web.wm.WMWebComponentInit");
        c.put("com.sankuai.eh.component.service.spi.IEHInit", hashMap44);
        HashMap hashMap45 = new HashMap(2);
        hashMap45.put("eh_component_web_viewbuilder", "com.sankuai.eh.component.web.widget.ComponentViewBuilder");
        c.put("com.sankuai.eh.component.service.spi.IViewBuilder", hashMap45);
        HashMap hashMap46 = new HashMap(3);
        hashMap46.put("mrn", "com.meituan.android.mrn.update.MRNPreDownload");
        hashMap46.put(ContainerInfo.ENV_MSC, "com.meituan.android.mercury.msc.adaptor.core.MSCAdaptorPreload");
        c.put("com.sankuai.meituan.ipredownload.IPreDownload", hashMap46);
        HashMap hashMap47 = new HashMap(2);
        hashMap47.put("ddd", "com.meituan.met.mercury.load.preload.DDLoaderPreload");
        c.put("com.sankuai.meituan.ipredownload.IPreDownloadDDD", hashMap47);
        HashMap hashMap48 = new HashMap(3);
        hashMap48.put("kernel", "com.sankuai.meituan.kernel.net.impl.INetFactoryImpl");
        hashMap48.put("wm_net_factory_impl", "com.sankuai.waimai.platform.net.service.INetFactoryImpl");
        c.put("com.sankuai.meituan.kernel.net.INetFactory", hashMap48);
        HashMap hashMap49 = new HashMap(2);
        hashMap49.put("skyeye", "com.sankuai.meituan.skyeye.library.core.SkyeyeMonitorImpl");
        c.put("com.sankuai.meituan.skyeye.library.core.ISkyeyeMonitor", hashMap49);
        HashMap hashMap50 = new HashMap(2);
        hashMap50.put("waimai_titans", "com.sankuai.waimai.business.titans.init.TitansInit");
        c.put("com.sankuai.titans.protocol.adaptor.IAppTitansInit", hashMap50);
        HashMap hashMap51 = new HashMap(49);
        hashMap51.put("addTitleBarElement", "com.sankuai.titans.jsbridges.base.uiextensions.AddTitleBarElementJsHandler");
        hashMap51.put("basic.webview.setHtmlTitle", "com.sankuai.titans.jsbridges.base.uiextensions.SetHtmlTitleJsHandler");
        hashMap51.put("checkVersion", "com.sankuai.titans.jsbridges.base.knb.CheckVersionJsHandler");
        hashMap51.put("closeWindow", "com.sankuai.titans.jsbridges.base.Interactions.CloseWindowJsHandler");
        hashMap51.put("dismissLoadingView", "com.sankuai.titans.jsbridges.base.uiextensions.DismissLoadingViewJsHandler");
        hashMap51.put("ffp.record", "com.meituan.android.common.weaver.impl.knb.FFPJsHandler");
        hashMap51.put("getPageState", "com.sankuai.titans.jsbridges.base.uiextensions.GetPageStateJsHandler");
        hashMap51.put("getSafeArea", "com.sankuai.titans.jsbridges.base.device.GetSafeAreaJsHandler");
        hashMap51.put("postMessage", "com.sankuai.titans.jsbridges.base.knb.PostMessageJsHandler");
        hashMap51.put(com.dianping.titans.utils.Constants.MULTI_PROCESS_PUBLISH_DATA, "com.sankuai.titans.jsbridges.base.Interactions.PublishJsHandler");
        hashMap51.put("ready", "com.sankuai.titans.jsbridges.base.Interactions.ReadyJsHandler");
        hashMap51.put("removeTitleBarElement", "com.sankuai.titans.jsbridges.base.uiextensions.RemoveTitleBarElementJsHandler");
        hashMap51.put("replaceTitleBarElement", "com.sankuai.titans.jsbridges.base.uiextensions.ReplaceTitleBarElementJsHandler");
        hashMap51.put("resetTitleBar", "com.sankuai.titans.jsbridges.base.uiextensions.ResetTitleBarJsHandler");
        hashMap51.put("setBackgroundColor", "com.sankuai.titans.jsbridges.base.uiextensions.SetBackgroundColorJsHandler");
        hashMap51.put("setImageTitle", "com.sankuai.titans.jsbridges.base.uiextensions.SetImageTitleJsHandler");
        hashMap51.put("setLLButton", "com.sankuai.titans.jsbridges.base.uiextensions.SetLLButtonJsHandler");
        hashMap51.put("setLRButton", "com.sankuai.titans.jsbridges.base.uiextensions.SetLRButtonJsHandler");
        hashMap51.put("setNavigationBar", "com.sankuai.titans.jsbridges.base.uiextensions.SetNavigationBarJsHandler");
        hashMap51.put("setNavigationBarHidden", "com.sankuai.titans.jsbridges.base.uiextensions.SetNavigationBarHiddenJsHandler");
        hashMap51.put("setRLButton", "com.sankuai.titans.jsbridges.base.uiextensions.SetRLButtonJsHandler");
        hashMap51.put("setRRButton", "com.sankuai.titans.jsbridges.base.uiextensions.SetRRButtonJsHandler");
        hashMap51.put("setSearchBar", "com.sankuai.titans.jsbridges.base.uiextensions.SetSearchBarJsHandler");
        hashMap51.put("setStatusBarStyle", "com.sankuai.titans.jsbridges.base.uiextensions.SetStatusBarStyleJsHandler");
        hashMap51.put(d.o, "com.sankuai.titans.jsbridges.base.uiextensions.SetTitleJsHandler");
        hashMap51.put("setTitleBar", "com.sankuai.titans.jsbridges.base.uiextensions.SetTitleBarJsHandler");
        hashMap51.put("setTitleBarAction", "com.sankuai.titans.jsbridges.base.uiextensions.SetTitleBarActionJsHandler");
        hashMap51.put("subscribe", "com.sankuai.titans.jsbridges.base.Interactions.SubscribeJsHandler");
        hashMap51.put("unsubscribe", "com.sankuai.titans.jsbridges.base.Interactions.UnsubscribeJsHandler");
        hashMap51.put("videortc.enterRoom", "com.sankuai.titans.live.video.bridge.rtc.EnterRoomLiveJsHandler");
        hashMap51.put("videortc.exitRoom", "com.sankuai.titans.live.video.bridge.rtc.ExitRoomJsHandler");
        hashMap51.put("videortc.muteAllRemoteAudio", "com.sankuai.titans.live.video.bridge.rtc.MuteAllRemoteAudioJsHandler");
        hashMap51.put("videortc.muteLocalAudio", "com.sankuai.titans.live.video.bridge.rtc.MuteLocalAudioJsHandler");
        hashMap51.put("videortc.setLocalViewFillMode", "com.sankuai.titans.live.video.bridge.rtc.SetLocalViewFillModeJsHandler");
        hashMap51.put("videortc.setSubRect", "com.sankuai.titans.live.video.bridge.rtc.SetSubRectJsHandler");
        hashMap51.put("videortc.switchCamera", "com.sankuai.titans.live.video.bridge.rtc.SwitchCameraJsHandler");
        c.put("com.sankuai.titans.protocol.jsbridge.AbsJsHandler", hashMap51);
        HashMap hashMap52 = new HashMap(2);
        hashMap52.put("knb-web-bridge-delegate", "com.dianping.titans.js.jshandler.DelegateHandlerFactory");
        c.put("com.sankuai.titans.protocol.jsbridge.IKnbWebBridgeDelegate", hashMap52);
        HashMap hashMap53 = new HashMap(2);
        hashMap53.put("TitansThreadPoolManager", "com.sankuai.titans.adapter.base.ThreadPoolService");
        c.put("com.sankuai.titans.protocol.services.IThreadPoolService", hashMap53);
        HashMap hashMap54 = new HashMap(2);
        hashMap54.put("TitansToastService", "com.sankuai.titans.adapter.base.ToastService");
        c.put("com.sankuai.titans.protocol.services.IToastService", hashMap54);
        HashMap hashMap55 = new HashMap(2);
        hashMap55.put("VerificationActivityDelegate", "com.sankuai.waimai.bussiness.order.confirm.verify.VerificationActivityDelegate");
        c.put("com.sankuai.waimai.bussiness.order.confirm.verify.yoda.YodaVerificationContract$View", hashMap55);
        HashMap hashMap56 = new HashMap(22);
        hashMap56.put("external_entrance_delegate", "com.sankuai.meituan.takeoutnew.ui.page.boot.SchemeProxyActivityDelegate");
        hashMap56.put("router_page/bindphone", "com.sankuai.waimai.business.page.passport.PreBindPhoneTransferDelegate");
        hashMap56.put("router_page/couponContainer", "com.sankuai.waimai.globalcart.rn.CouponPopupContainer");
        hashMap56.put("router_page/goodscollection", "com.sankuai.waimai.business.restaurant.rn.bridge.ShopCartRNBridgeDelegate");
        hashMap56.put("router_page/locatemanuallymmp", "com.sankuai.waimai.business.address.msi.LocateManuallyActivityDelegate");
        hashMap56.put("router_page/wmverification", "com.sankuai.waimai.bussiness.order.confirm.verify.VerificationActivityDelegate");
        hashMap56.put("router_uri/account/bindphone", "com.sankuai.waimai.business.page.passport.PreBindPhoneTransferDelegate");
        hashMap56.put("router_uri/b2cimmessage", "com.sankuai.waimai.business.im.prepare.PrepareChatPageTransferDelegate");
        hashMap56.put("router_uri/chat/1001", "com.sankuai.waimai.business.im.prepare.PrepareChatPageTransferDelegate");
        hashMap56.put("router_uri/chat/1025", "com.sankuai.waimai.business.im.group.prepare.BaseGroupChatTransferDelegate");
        hashMap56.put("router_uri/chat/1036", "com.sankuai.waimai.business.im.group.prepare.BaseGroupChatTransferDelegate");
        hashMap56.put("router_uri/chat/1050", "com.sankuai.waimai.business.im.group.prepare.BaseGroupChatTransferDelegate");
        hashMap56.put("router_uri/goodscollections", "com.sankuai.waimai.business.restaurant.rn.bridge.ShopCartRNBridgeDelegate");
        hashMap56.put("router_uri/immessage", "com.sankuai.waimai.business.im.prepare.PrepareChatPageTransferDelegate");
        hashMap56.put("router_uri/locatemanuallymmp", "com.sankuai.waimai.business.address.msi.LocateManuallyActivityDelegate");
        hashMap56.put("scheme_dispatch_delegate", "com.sankuai.meituan.takeoutnew.ui.page.boot.SchemeDispatchActivityDelegate");
        c.put("com.sankuai.waimai.foundation.core.base.activity.transfer.BaseActivityDelegate", hashMap56);
        HashMap hashMap57 = new HashMap(3);
        hashMap57.put("BaseGroupChatTransferDelegate", "com.sankuai.waimai.business.im.group.prepare.BaseGroupChatTransferDelegate");
        hashMap57.put("PrepareChatPageTransferDelegate", "com.sankuai.waimai.business.im.prepare.PrepareChatPageTransferDelegate");
        c.put("com.sankuai.waimai.foundation.core.base.activity.transfer.LaunchModeProvider", hashMap57);
        HashMap hashMap58 = new HashMap(2);
        hashMap58.put("IAdManagerService", "com.sankuai.waimai.ad.mads.IAdManagerServiceImpl");
        c.put("com.sankuai.waimai.foundation.core.service.ad.IAdManagerService", hashMap58);
        HashMap hashMap59 = new HashMap(2);
        hashMap59.put("SchemeProxyActivityDelegate", "com.sankuai.meituan.takeoutnew.ui.page.boot.SchemeDispatchActivityDelegate");
        c.put("com.sankuai.waimai.foundation.location.v2.callback.DeviceLocateCallback", hashMap59);
        HashMap hashMap60 = new HashMap(62);
        hashMap60.put("countdown", "com.sankuai.waimai.mach.component.countdown.CountDownTagProcessor");
        hashMap60.put("embed", "com.sankuai.waimai.platform.mach.extension.nested.EmbedProcessor");
        hashMap60.put("embedv2", "com.sankuai.waimai.platform.mach.extension.nestedv2.EmbedProcessorV2");
        hashMap60.put("flash-member-price", "com.sankuai.waimai.store.view.standard.mach.FlashMemberPriceProcessor");
        hashMap60.put("flash-price", "com.sankuai.waimai.store.view.standard.mach.FlashPriceProcessor");
        hashMap60.put("indicator", "com.sankuai.waimai.mach.component.indicator.IndicatorTagProcessor");
        hashMap60.put("infinite-canvas", "com.sankuai.waimai.irmo.canvas.mach.MachCanvasProcessor");
        hashMap60.put("irmo-effect", "com.sankuai.waimai.irmo.render.IrmoEffectTagProcessor");
        hashMap60.put(ConfigInfo.MODULE_KING_KONG, "com.sankuai.waimai.store.mach.kingkongscroller.KingKongScrollerTagProcessor");
        hashMap60.put("med-kano-tag-rich-text", "com.sankuai.waimai.store.drug.search.mach.component.kanotagspuname.KanoTagSpuNameProcessor");
        hashMap60.put("med-price-view", "com.sankuai.waimai.store.platform.domain.core.goods.newStylePrice.machandprice.HandPriceMachProcessor");
        hashMap60.put("pouch-ad-swiper", "com.sankuai.waimai.pouch.mach.swiper.PouchSwiperTagProcessor");
        hashMap60.put("pouch-ad-tab", "com.sankuai.waimai.pouch.mach.tab.PouchTabTagProcessor");
        hashMap60.put("pouch-ad-text", "com.sankuai.waimai.pouch.mach.text.PouchTextProcessor");
        hashMap60.put("pouchembed", "com.sankuai.waimai.ad.view.mach.nested.PouchEmbedProcessor");
        hashMap60.put("roo-image", "com.sankuai.waimai.platform.mach.rooimage.RooImageProcessor");
        hashMap60.put("scroller", "com.sankuai.waimai.mach.component.scroller.ScrollerTagProcessor");
        hashMap60.put("sg-poi-dynamic-tag", "com.sankuai.waimai.store.mach.dynamic_tag.DynamicPoiTagProcessor");
        hashMap60.put("sg-poi-recommend-view", "com.sankuai.waimai.store.mach.recommendtag.RecommendTagProcessor");
        hashMap60.put("sg-scroller", "com.sankuai.waimai.store.view.standard.mach.SGScrollerProcessor");
        hashMap60.put("sg-spring-back-wrapper", "com.sankuai.waimai.store.view.standard.mach.SGSpringBackWrapperProcessor");
        hashMap60.put("sm-dynamic-tag", "com.sankuai.waimai.store.mach.sm_dynamic_tag.SMDynamicTagProcessor");
        hashMap60.put("sm-unify-price", "com.sankuai.waimai.store.view.price.mach.SCPriceViewMachProcessor");
        hashMap60.put("smart-image", "com.sankuai.waimai.store.mach.image.SmartImageProcessor");
        hashMap60.put("swiper", "com.sankuai.waimai.mach.component.swiper.SwiperTagProcessor");
        hashMap60.put("swiper-fade-effect", "com.sankuai.waimai.business.page.home.list.future.mach.transitionanimation.TransitionAnimationProcessor");
        hashMap60.put("universal-image-view", "com.sankuai.waimai.store.drug.mach.component.image.CompatImageProcessor");
        hashMap60.put("wm-animation-view", "com.sankuai.waimai.platform.mach.animation.AnimationViewProcessor");
        hashMap60.put("wm-cake-order-edit-text", "com.sankuai.waimai.platform.mach.order.CakeEditTextTagProcessor");
        hashMap60.put("wm-dynamic-image", "com.sankuai.waimai.business.page.home.list.future.mach.DynamicImageTagProcessor");
        hashMap60.put("wm-dynamic-tag", "com.sankuai.waimai.platform.mach.tag.DynamicTagProcessor");
        hashMap60.put("wm-effect", "com.sankuai.waimai.irmo.mach.effect.WmEffectTagProcessor");
        hashMap60.put("wm-gif-image", "com.sankuai.waimai.ad.view.mach.gifimage.GifImageTagProcessor");
        hashMap60.put("wm-im-rich-text", "com.sankuai.waimai.business.im.common.mach.LinkTextViewProcessor");
        hashMap60.put("wm-item-video", "com.sankuai.waimai.ad.view.mach.itemvideo.ItemVideoTagProcessor");
        hashMap60.put("wm-lottie", "com.sankuai.waimai.platform.mach.lottieextend.LottieTagProcessor");
        hashMap60.put("wm-order-edit-text", "com.sankuai.waimai.platform.mach.order.EditTextTagProcessor");
        hashMap60.put("wm-order-rich-text", "com.sankuai.waimai.platform.mach.order.OrderRichTextProcessor");
        hashMap60.put("wm-order-rich-text-comp", "com.sankuai.waimai.platform.mach.order.OrderRichTextProcessorComp");
        hashMap60.put("wm-rating-bar", "com.sankuai.waimai.search.common.mach.component.WMRatingBarTagProcessor");
        hashMap60.put("wm-rating-crown", "com.sankuai.waimai.business.page.home.list.future.mach.RateCrownTagProcessor");
        hashMap60.put("wm-tier-slide", "com.sankuai.waimai.ad.view.mach.tierslide.TierSlideTagProcessor");
        hashMap60.put("wm-vap", "com.sankuai.waimai.irmo.mach.vap.VapTagProcessor");
        hashMap60.put("wm-video", "com.sankuai.waimai.platform.mach.videoextend.VideoTagProcessor");
        hashMap60.put("wm-video-player", "com.sankuai.waimai.irmo.mach.video.VideoPlayerTagProcessor");
        hashMap60.put("wm-webp-image", "com.sankuai.waimai.platform.mach.webpimage.WebpImageTagProcessor");
        c.put("com.sankuai.waimai.mach.ITagProcessor", hashMap60);
        HashMap hashMap61 = new HashMap(15);
        hashMap61.put(TensorConfig.KEY_INPUT_ARRAY, "com.sankuai.waimai.platform.machpro.textarea.MPInputComponent");
        hashMap61.put(MLivePlayerModule.REACT_CLASS, "com.sankuai.waimai.business.ugc.machpro.live.MPLivePlayerComponent");
        hashMap61.put("lottie", "com.sankuai.waimai.platform.machpro.component.lottie.MPLottieComponent");
        hashMap61.put("textarea", "com.sankuai.waimai.platform.machpro.textarea.MPTextAreaComponent");
        hashMap61.put("waterfall", "com.sankuai.waimai.business.ugc.machpro.waterfall.MPWaterfallComponent");
        hashMap61.put("wm-activity-input", "com.sankuai.waimai.platform.machpro.input.WMActivityInputComponent");
        hashMap61.put("wm-draggable", "com.sankuai.waimai.business.restaurant.poicontainer.machpro.draglist.MPDragComponent");
        hashMap61.put("wm-dynamic-tag", "com.sankuai.waimai.platform.machpro.component.tag.MPDynamicTagComponent");
        hashMap61.put("wm-nested-scroll-view", "com.sankuai.waimai.business.ugc.machpro.nestedscroll.MPNestedScrollComponent");
        hashMap61.put("wm-video", "com.sankuai.waimai.platform.machpro.video.MPVideoComponent");
        hashMap61.put("wm-zoom-image", "com.sankuai.waimai.business.ugc.machpro.components.MPZoomImageComponent");
        c.put("com.sankuai.waimai.machpro.component.MPComponent", hashMap61);
        HashMap hashMap62 = new HashMap(13);
        hashMap62.put("ComboModule", "com.sankuai.waimai.business.restaurant.poicontainer.machpro.menu.ComboModule");
        hashMap62.put("MPCartModule", "com.sankuai.waimai.business.restaurant.base.skuchoose.MPCartModule");
        hashMap62.put("MPMenuModule", "com.sankuai.waimai.business.restaurant.poicontainer.machpro.menu.MPMenuModule");
        hashMap62.put("MPShopCartModule", "com.sankuai.waimai.business.restaurant.poicontainer.machpro.menu.MPShopCartModule");
        hashMap62.put("StatusBar", "com.sankuai.waimai.platform.machpro.module.MPStatusBarModule");
        hashMap62.put("WMCalendar", "com.sankuai.waimai.business.ugc.machpro.module.calendar.WMCalendarModule");
        hashMap62.put("WMMPMineLogicModule", "com.sankuai.waimai.business.page.mine.module.MP_MineLogicModule");
        hashMap62.put("WMVideo", "com.sankuai.waimai.platform.machpro.video.WMVideoPreloadModule");
        hashMap62.put("dovemon", "com.sankuai.waimai.platform.monitor.DoveMPModule");
        c.put("com.sankuai.waimai.machpro.module.MPModule", hashMap62);
        HashMap hashMap63 = new HashMap(2);
        hashMap63.put("ShopCartRNBridgeDelegate", "com.sankuai.waimai.business.restaurant.rn.bridge.ShopCartRNBridgeDelegate");
        c.put("com.sankuai.waimai.platform.domain.manager.observers.OrderGoodObserver", hashMap63);
        HashMap hashMap64 = new HashMap(25);
        hashMap64.put("alita-intention", "com.sankuai.waimai.ad.interact.AlitaIntentionPlugin");
        hashMap64.put("container-life-cycle", "com.sankuai.waimai.pouch.plugin.common.interact.WMPouchContainerLifeCyclePlugin");
        hashMap64.put("dessert-drink-link", "com.sankuai.waimai.ad.interact.DessertDrinkLinkInteractPlugin");
        hashMap64.put("embed-render-success-opportunity", "com.sankuai.waimai.ad.interact.EmbedLifeCyclePlugin");
        hashMap64.put("infinite-canvas-by-view-id", "com.sankuai.waimai.ad.interact.irmo.CanvasByViewIdPlugin");
        hashMap64.put("infinite-canvas-zone-check", "com.sankuai.waimai.ad.interact.irmo.CanvasZoneCheckPlugin");
        hashMap64.put("irmo-effect-by-category-identifier", "com.sankuai.waimai.ad.interact.irmo.IrmoEffectByCategoryIDPlugin");
        hashMap64.put("irmo-effect-by-view-id-dsl", "com.sankuai.waimai.ad.interact.irmo.IrmoEffectByViewIdDSLPlugin");
        hashMap64.put("irmo-vap-by-view-id", "com.sankuai.waimai.ad.interact.irmo.VapByViewIdPlugin");
        hashMap64.put("irmo-vap-zone-check", "com.sankuai.waimai.ad.interact.irmo.VapZoneCheckPlugin");
        hashMap64.put("irmo-zone-check", "com.sankuai.waimai.ad.interact.irmo.IrmoZoneCheckPlugin");
        hashMap64.put("platinum-item-video", "com.sankuai.waimai.ad.interact.PlatinumItemVideoInteractPlugin");
        hashMap64.put("platinum-video", "com.sankuai.waimai.ad.interact.PlatinumVideoInteractPlugin");
        hashMap64.put("tile-swiper", "com.sankuai.waimai.ad.interact.TileSwiperInteractPlugin");
        hashMap64.put("vertical-image-swiper", "com.sankuai.waimai.ad.interact.WMVerticalImageInteractPlugin");
        hashMap64.put("vertical-tab-swiper", "com.sankuai.waimai.ad.interact.VerticalTabSwiperPlugin");
        hashMap64.put("vertical-text-swiper", "com.sankuai.waimai.ad.interact.VerticalTextSwiperPlugin");
        hashMap64.put("wm-gif", "com.sankuai.waimai.ad.interact.WMGifInteractPlugin");
        c.put("com.sankuai.waimai.pouch.plugin.protocol.AbsWMPouchInteractPlugin", hashMap64);
        HashMap hashMap65 = new HashMap(5);
        hashMap65.put("pouch_common_report_procedure", "com.sankuai.waimai.ad.report.PouchCommonReportPlugin");
        hashMap65.put("waimai_common_report_procedure", "com.sankuai.waimai.ad.report.WMCommonReportPlugin");
        hashMap65.put("waimai_platinum_report_procedure", "com.sankuai.waimai.ad.report.WMPlatinumReportPlugin");
        c.put("com.sankuai.waimai.pouch.plugin.protocol.AbsWMPouchReportPlugin", hashMap65);
        HashMap hashMap66 = new HashMap(5);
        hashMap66.put(PouchDynamicAd.CONTAINER_ID_POUCH_COMMON, "com.sankuai.waimai.ad.view.mach.pouchview.PouchCommonAdMachView");
        hashMap66.put(PouchDynamicAd.CONTAINER_ID_POUCH_MACH_POPUP, "com.sankuai.waimai.ad.view.mach.pouchview.WMPouchMachPopupView");
        hashMap66.put(PouchDynamicAd.CONTAINER_ID_WM_COMMON, "com.sankuai.waimai.ad.view.mach.pouchview.WMPouchAdMachView");
        c.put("com.sankuai.waimai.pouch.view.PouchAdView", hashMap66);
        HashMap hashMap67 = new HashMap(2);
        hashMap67.put("IAdChargeManagerService", "com.sankuai.waimai.ad.mads.IAdChargeManagerServiceImpl");
        c.put("com.sankuai.waimai.report.IAdChargeManagerService", hashMap67);
        HashMap hashMap68 = new HashMap(2);
        hashMap68.put("skyFallContainer", "com.sankuai.waimai.popup.SkyFallTypeViewFactory");
        c.put("com.sankuai.waimai.touchmatrix.rebuild.factory.TypeViewFactory", hashMap68);
    }

    public static boolean a() {
        return e;
    }

    public static void a(Context context) {
        Object[] objArr = {context};
        ChangeQuickRedirect changeQuickRedirect = a;
        if (PatchProxy.isSupport(objArr, null, changeQuickRedirect, true, "165cc1a3836df12e26169154d7470400", RobustBitConfig.DEFAULT_VALUE)) {
            PatchProxy.accessDispatch(objArr, null, changeQuickRedirect, true, "165cc1a3836df12e26169154d7470400");
        } else if (context == null || context.getApplicationContext() == null) {
        } else {
            d = context.getApplicationContext();
        }
    }

    public static Map<String, Map<String, String>> b() {
        Object[] objArr = new Object[0];
        ChangeQuickRedirect changeQuickRedirect = a;
        if (PatchProxy.isSupport(objArr, null, changeQuickRedirect, true, "edfb321d40ec0084bb24441f2f61300a", RobustBitConfig.DEFAULT_VALUE)) {
            return (Map) PatchProxy.accessDispatch(objArr, null, changeQuickRedirect, true, "edfb321d40ec0084bb24441f2f61300a");
        }
        d();
        HashMap hashMap = new HashMap();
        if (c != null && !c.isEmpty()) {
            for (Map.Entry<String, Map<String, String>> entry : c.entrySet()) {
                HashMap hashMap2 = new HashMap();
                if (entry.getValue() != null) {
                    hashMap2.putAll(entry.getValue());
                }
                hashMap.put(entry.getKey(), hashMap2);
            }
        }
        return hashMap;
    }

    private static synchronized void d() {
        synchronized (b.class) {
            Object[] objArr = new Object[0];
            ChangeQuickRedirect changeQuickRedirect = a;
            if (PatchProxy.isSupport(objArr, null, changeQuickRedirect, true, "a525bbe7128ad5f622f88f095339b503", RobustBitConfig.DEFAULT_VALUE)) {
                PatchProxy.accessDispatch(objArr, null, changeQuickRedirect, true, "a525bbe7128ad5f622f88f095339b503");
            } else if (e) {
            } else {
                c();
                HashMap hashMap = new HashMap(7);
                b = hashMap;
                hashMap.put("com.meituan.android.common.aidata.lightblue.LightBlueImpl", Void.class);
                b.put("com.sankuai.meituan.kernel.net.impl.INetFactoryImpl", Void.class);
                b.put("com.sankuai.waimai.business.titans.init.TitansInit", Void.class);
                b.put("com.sankuai.waimai.ad.mads.IAdChargeManagerServiceImpl", Void.class);
                b.put("com.sankuai.waimai.ad.mads.IAdManagerServiceImpl", Void.class);
                if (c == null) {
                    c = Collections.emptyMap();
                }
                if (b == null) {
                    b = Collections.emptyMap();
                }
                e = true;
            }
        }
    }

    public static void a(Context context, a aVar) {
        Object[] objArr = {context, aVar};
        ChangeQuickRedirect changeQuickRedirect = a;
        if (PatchProxy.isSupport(objArr, null, changeQuickRedirect, true, "282d536d8fc59b3c6167afa55c6bc9e3", RobustBitConfig.DEFAULT_VALUE)) {
            PatchProxy.accessDispatch(objArr, null, changeQuickRedirect, true, "282d536d8fc59b3c6167afa55c6bc9e3");
            return;
        }
        if (aVar != null) {
            f = aVar;
        }
        a(context);
        d();
    }

    private static ClassLoader e() {
        Object[] objArr = new Object[0];
        ChangeQuickRedirect changeQuickRedirect = a;
        return PatchProxy.isSupport(objArr, null, changeQuickRedirect, true, "dc0fcc5ccc862b269f86b8055ad6e5dc", RobustBitConfig.DEFAULT_VALUE) ? (ClassLoader) PatchProxy.accessDispatch(objArr, null, changeQuickRedirect, true, "dc0fcc5ccc862b269f86b8055ad6e5dc") : d == null ? b.class.getClassLoader() : d.getClassLoader();
    }

    private static Map<String, String> a(String str, String str2) {
        Object[] objArr = {str, str2};
        ChangeQuickRedirect changeQuickRedirect = a;
        if (PatchProxy.isSupport(objArr, null, changeQuickRedirect, true, "df33d9d6a176c130c0f44a35a6ee0917", RobustBitConfig.DEFAULT_VALUE)) {
            return (Map) PatchProxy.accessDispatch(objArr, null, changeQuickRedirect, true, "df33d9d6a176c130c0f44a35a6ee0917");
        }
        d();
        Map<String, String> map = c.get(str);
        if (map == null || map.isEmpty()) {
            return Collections.emptyMap();
        }
        if (TextUtils.isEmpty(str2)) {
            return map;
        }
        String str3 = map.get(str2);
        if (TextUtils.isEmpty(str3)) {
            return Collections.emptyMap();
        }
        return Collections.singletonMap(str2, str3);
    }

    public static <T> List<T> a(Class<T> cls, String str) {
        Object[] objArr = {cls, str};
        ChangeQuickRedirect changeQuickRedirect = a;
        return PatchProxy.isSupport(objArr, null, changeQuickRedirect, true, "4a704bff36098e75524e1f9dbd61597e", RobustBitConfig.DEFAULT_VALUE) ? (List) PatchProxy.accessDispatch(objArr, null, changeQuickRedirect, true, "4a704bff36098e75524e1f9dbd61597e") : a(cls, str, null);
    }

    @Deprecated
    public static <T> List<T> a(Class<T> cls, String str, Object... objArr) {
        Object[] objArr2 = {cls, str, objArr};
        ChangeQuickRedirect changeQuickRedirect = a;
        if (PatchProxy.isSupport(objArr2, null, changeQuickRedirect, true, "3a8e2fcc30b0b9377105ab83b2b42d79", RobustBitConfig.DEFAULT_VALUE)) {
            return (List) PatchProxy.accessDispatch(objArr2, null, changeQuickRedirect, true, "3a8e2fcc30b0b9377105ab83b2b42d79");
        }
        if (cls == null) {
            return Collections.emptyList();
        }
        Map<String, String> a2 = a(cls.getName(), str);
        if (a2.isEmpty()) {
            return Collections.emptyList();
        }
        ArrayList arrayList = new ArrayList(a2.size());
        ClassLoader e2 = e();
        for (Map.Entry<String, String> entry : a2.entrySet()) {
            String value = entry.getValue();
            if (!TextUtils.isEmpty(value)) {
                Object a3 = com.sankuai.meituan.serviceloader.a.a(e2, value, objArr);
                if (a3 == null) {
                    a(new Exception("serviceloader fail to create instance for key=" + entry.getKey() + " className=" + value));
                } else {
                    arrayList.add(a3);
                }
            }
        }
        return arrayList;
    }

    public static void a(Throwable th) {
        Object[] objArr = {th};
        ChangeQuickRedirect changeQuickRedirect = a;
        if (PatchProxy.isSupport(objArr, null, changeQuickRedirect, true, "93cf5254629e41d53bc55bef738e1394", RobustBitConfig.DEFAULT_VALUE)) {
            PatchProxy.accessDispatch(objArr, null, changeQuickRedirect, true, "93cf5254629e41d53bc55bef738e1394");
        } else if (f != null) {
            f.a(th);
        }
    }
}
