package com.dianping.richtext;

import com.dianping.titans.widget.DynamicTitleParser;
import com.meituan.android.neohybrid.core.config.UIConfig;
import com.meituan.robust.common.CommonConstant;
import com.sankuai.waimai.monitor.model.ErrorCode;
import java.util.HashMap;
/* compiled from: ProGuard */
/* loaded from: classes.dex */
public final class d {
    public static String A = "ts";
    public static String B = "fn";
    public static String C = "h";
    public static String D = "w";
    public static String E = "u";
    public static String F = "in";
    public static String G = "lk";
    public static String H = "la";
    public static HashMap<String, String> I = null;
    public static HashMap<String, String> J = null;
    public static HashMap<String, String> K = null;
    public static String a = "al";
    public static String b = "va";
    public static String c = "ls";
    public static String d = "rl";
    public static String e = "lc";
    public static String f = "sc";
    public static String g = "ec";
    public static String h = "go";
    public static String i = "cr";
    public static String j = "rc";
    public static String k = "bc";
    public static String l = "bw";
    public static String m = "fhi";
    public static String n = "pd";
    public static String o = "pdt";
    public static String p = "pdr";
    public static String q = "pdb";
    public static String r = "pdl";
    public static String s = "tp";
    public static String t = "te";
    public static String u = "tst";
    public static String v = "ke";
    public static String w = "bgc";
    public static String x = "tc";
    public static String y = "st";
    public static String z = "ul";

    static {
        HashMap<String, String> hashMap = new HashMap<>();
        I = hashMap;
        hashMap.put(a, "alignment");
        I.put(b, "verticalalignment");
        I.put(c, "linespacing");
        I.put(d, "richtextlist");
        I.put(e, "labelcolor");
        I.put(f, "startcolor");
        I.put(g, "endcolor");
        I.put(h, "gradientorientation");
        I.put(i, "cornerradius");
        I.put(j, "rectcorner");
        I.put(k, "bordercolor");
        I.put(l, "borderwidth");
        I.put(m, "firstlineheadindent");
        I.put(n, "padding");
        I.put(o, "paddingtop");
        I.put(p, "paddingright");
        I.put(q, "paddingbottom");
        I.put(r, "paddingleft");
        I.put(t, "text");
        I.put(u, "textstyle");
        I.put(v, "kerning");
        I.put(w, UIConfig.BACKGROUND_COLOR);
        I.put(x, "textcolor");
        I.put(y, "strikethrough");
        I.put(z, DynamicTitleParser.PARSER_VAL_FONT_STYLE_UNDERLINE);
        I.put(A, "textsize");
        I.put(B, "fontname");
        HashMap<String, String> hashMap2 = new HashMap<>();
        J = hashMap2;
        hashMap2.put("0", "\ue90e");
        J.put("1", "\ue90f");
        J.put("2", "\ue910");
        J.put("3", "\ue911");
        J.put("4", "\ue912");
        J.put("5", "\ue913");
        J.put("6", "\ue914");
        J.put("7", "\ue915");
        J.put("8", "\ue916");
        J.put("9", "\ue917");
        J.put(CommonConstant.Symbol.DOT, "\ue918");
        HashMap<String, String> hashMap3 = new HashMap<>();
        K = hashMap3;
        hashMap3.put("A", "\ue938");
        K.put(ErrorCode.ERROR_TYPE_B, "\ue939");
        K.put("C", "\ue93a");
        K.put("D", "\ue93b");
        K.put("E", "\ue93c");
        K.put("F", "\ue93d");
        K.put("G", "\ue93e");
        K.put(ErrorCode.ERROR_TYPE_H, "\ue93f");
        K.put("I", "\ue940");
        K.put("J", "\ue941");
        K.put("K", "\ue942");
        K.put("L", "\ue943");
        K.put(ErrorCode.ERROR_TYPE_M, "\ue944");
        K.put(ErrorCode.ERROR_TYPE_N, "\ue945");
        K.put("O", "\ue92e");
        K.put("P", "\ue92f");
        K.put("Q", "\ue946");
        K.put("R", "\ue947");
        K.put("S", "\ue948");
        K.put("T", "\ue932");
        K.put("U", "\ue949");
        K.put("V", "\ue94a");
        K.put("W", "\ue94b");
        K.put("X", "\ue94c");
        K.put("Y", "\ue94d");
        K.put("Z", "\ue94e");
    }
}
